[#chapter-four]
= Bibliothèque Publique d’Ottawa - Succursale Cumberland

[.text-right]
*Vendredi 29 juillet 2016* - __14:45 - 20 degrés Celsius__

Je suis à la bibliothèque de Cumberland. Je me sens fébrile quant à l’aventure à laquelle je me prépare. La préparation pour mon voyage est presque complète. Par contre, il ne faut surtout pas que j’oublie de passer à la quincaillerie la plus proche pour acheter une petite lanterne de camping. Ensuite, je vais l’insérer dans la valise de gauche. Cette valise se trouve sur le côté gauche du porte-bagage arrière de mon vélo. Il faut aussi que je trouve des sacs en plastique, deux ou trois peut-être. C’est ce qui me manque dans ma liste. Je crois pouvoir les insérer dans la valise de droite.

Soudain, j’ai une interrogation parce que j’ai un trou de mémoire, est-ce qu’on dit un sac plastique ou un sachet plastique ? Comme à l’habitude dans des situations pareilles, quand vient le moment de la culpabilité, je m’apitoie sur moi-même et je suis mon pire juge, car je hurle en moi-même : «Tu devrais le savoir après toutes ces années. Pourquoi est-ce que t’as pas retenu la leçon ? Tu trouves toujours le moyen de perdre ton temps, de tout foutre en l’air. Tu cogites trop bon sang !»

Je n’aime pas du tout quand je suis mon pire juge, mais en des moments où je m’apitoie sur moi-même, on dirait que ça me réconforte de me faire mal, d’être sévère envers moi-même.
Je sens que j’ai un de ces maux de tête, un symptôme que j’ai quand je me mange la laine sur le dos ! J’ai hâte à demain ! J’ai hâte au voyage ! J’ai hâte à l’aventure ! Peut-être ou sûrement que le fait de changer d’air fera en sorte que je ne penserai plus à mes problèmes. Mes problèmes ! Pourquoi est-ce qu’un incapable comme moi a voulu s’enfoncer de 2000 $ dans les dettes ? Dans ces temps difficiles, comment est-ce que je pourrais me permettre de perdre 2000 $? Quand je pense à tout ce qui me tracasse, mon mal de tête augmente. Il faut que je me relaxe, que je retrouve ma respiration et de toute façon ce n’est pas bien d’avoir l’esprit embrouillé dans un sanctuaire. Il faut que je décompresse pour pouvoir mettre de l’ordre dans mon esprit. Toutes ces pensées erratiques ne m’avancent à rien. Je me dis à voix basse et lentement dans ma tête de décompresser, de relaxer, de respirer, de décrire la bibliothèque jusqu’à ce que je me sente apaisé. J’ai l’impression que mon esprit est en train de me chuchoter « à chacun son médicament».

Pour me détendre l’esprit, je vais décrire la bibliothèque. Je vais décrire dans mon journal intime ce que je sais de la succursale Cumberland ou du moins jusqu’à ce que je sente que mon esprit soit apaisé, que le sentiment d’irritation se change en tranquillité.

Je suis présentement à la succursale Cumberland qui fait partie de la Bibliothèque Publique d’Ottawa (BPO). La succursale est située dans l’arrondissement d’Orléans. Ce dernier est situé dans la partie est de la ville d’Ottawa, à une vingtaine de minutes en voiture du centre-ville d’Ottawa. L’édifice de la succursale Cumberland a été inauguré en 1999 par le maire Brian Coburn. À l’époque de son inauguration, le zonage était différent, ce qui fait que la bibliothèque était située dans le canton de Cumberland et la succursale s’appelait la bibliothèque de Cumberland. Le premier janvier 2001, plusieurs banlieues ont été fusionnées à la ville d’Ottawa, dont le canton de Cumberland. Orléans, autrefois appelé ville d’Orléans, vit la superficie de son territoire augmenter parce qu’on a modifié l’étendue de la municipalité de Cumberland ainsi que celle de Gloucester.

En résumé depuis 2001, la bibliothèque fait désormais partie du réseau de la Bibliothèque Publique d’Ottawa (BPO). J’ajouterai aussi que chaque bibliothèque du réseau de la BPO est plus souvent désignée par le nom de succursale.

L’édifice de la succursale Cumberland est annexé au complexe récréatif Ray Friel. De l’aire de stationnement extérieur, quand on entre dans le bâtiment, il faut suivre un couloir pour accéder à la bibliothèque.

Pour parler de l’aménagement des espaces, je dirai ceci. La bibliothèque est divisée en deux principales sections : une pour adulte et une pour enfant. Chaque section de la bibliothèque contient plusieurs aires et parfois plusieurs salles. Par exemple, dans la section destinée aux adultes, il y a aussi une aire contenant la collection de documents pour adolescents, une salle de postes informatiques, une salle où l’on retrouve des documents sur l’histoire du Canton de Cumberland, une aire de détente disposant de quelques sofas et d’un foyer. On se sent chez soi à la bibliothèque quand on lit un livre dans cette aire.
La bibliothèque dispose de plusieurs types de mobilier. Si je me concentre sur les tables, je dirai ceci : elles ont deux principales fonctions, soit pour la consultation de documents ou pour le travail individuel. Je dénombre deux ensembles de carrels ayant la capacité de cinq personnes chacun. Un carrel est une sorte de pupitre caractérisé par la disposition d’une cloison de chacun des côtés latéraux de la table ou de l’espace de travail, faisant en sorte que les gens y travaillant ne soient pas distraits par ce qui se passe autour. Je trouve que c’est très utile pour ma concentration quand je veux faire un devoir. Chaque carrel a aussi un passe-câble. Le passe-câble est un tube qui enrobe l’œillet, ce dernier est un trou d’un diamètre d’environ deux pouces, pour que l’usager puisse pouvoir y passer un ou des câbles : le câble d’alimentation d’un ordinateur portable, par exemple.

Grâce à Dieu, je suis dans une bibliothèque ! Mon moment de détente pour décrire la bibliothèque m’a fait du bien. Je me sens moins tendu qu’auparavant. À chacun son médicament ! Pour continuer d’écrire le fil de mes idées interrompues tantôt par des angoisses, j’ai décidé d’aller faire un voyage à vélo d’Ottawa jusqu’à la ville de North Bay. J’aime les bibliothèques, alors j’ai comme objectif d’en visiter le plus possible en faisant mon voyage. Je n’ai jamais été à North Bay et je ne connais rien de cette ville. En fait, mon plan initial était de me rendre au parc Algonquin en sillonnant les routes à vélo pour m’arrêter dans des bibliothèques puis de retourner à Ottawa ensuite, mais j’ai remarqué que la majorité des bibliothèques se trouve le long de la rivière des Outaouais et qu’une grande partie de la route que j’allais emprunter pour me rendre jusqu’au parc Algonquin n’avait pas beaucoup de bibliothèques. Comme c’est mon premier voyage à vélo, je ne crois pas que je m’en voudrais si je n’atteignais pas North Bay, mais si je dépasse cette ville pour me rendre encore plus loin, je serai très content.

Je veux expérimenter le plus de bibliothèques publiques que possible. J’aime les bibliothèques publiques, parce qu’elles sont un peu comme un microcosme de la culture de la communauté locale. Aussi, je peux me renseigner sur la ville que je visite auprès des employés de la bibliothèque et des usagers. Je peux m’informer sur les auteurs, les artistes et les PME locaux de la communauté. Je peux aussi consulter la collection de documents pour mieux connaître la ville. Chaque bibliothèque a une empreinte documentaire qui lui est propre parce qu’elle veut desservir sa propre population. La démographie d’un quartier à Ottawa est différente de celle d’une ville en région. Par conséquent, les documents qui se trouvent dans un quartier d’Ottawa et ceux d’une ville en région seront différents. Je trouve que les bibliothèques publiques sont un espace de savoir, un espace de communication, un espace familial et une zone franche. C’est un espace actif aussi. Je trouve que c’est l’endroit idéal pour m’arrêter si je veux connaître la ville que je veux visiter.

J’ai huit jours de vacances alors j’en profite pour partir à l’aventure. Je consacre la majeure partie de mes vacances au voyage à vélo. Je prévois prendre les deux derniers jours pour me reposer. Donc, trois jours pour me rendre à ma destination et trois jours pour retourner à la maison ce qui fait que la durée du voyage est au max 6 jours. C’est la raison pour laquelle je me dis que je ne m’en voudrais pas trop si je n’atteins pas North Bay. Je me suis préparé physiquement pour la randonnée en faisant deux heures et demie de pratique par jour de vélo stationnaire durant les trois dernières semaines. Une heure le matin et une heure et demie le soir. Je voulais que mon corps s’habitue pour le voyage.

Je travaille comme opérateur de presse dans une compagnie d’imprimerie. Au boulot, dans mon département, je m’occupe principalement d’imprimer des livres et des manuels scolaires. Mes vacances de huit jours ont commencé aujourd’hui et vont se terminer samedi de la semaine prochaine. Je suis allé récupérer mon vélo ce matin dans un atelier de réparation. Par mesure de précaution, je voulais que mon vélo soit inspecté par un professionnel avant d’entreprendre le voyage.

J’avais prévu faire ce périple à vélo depuis près d’un mois, mais je n’avais pas prévu le commencer en ayant l’esprit perturbé par une mauvaise nouvelle comme celle que j’ai eue hier et que je ne peux dévoiler parce que je n’ai pas encore tout à fait les mots pour exprimer le pétrin dans lequel je me suis enfoncé. Ce qui est sûr, c’est que je ferai mon excursion pour me ressourcer. J’ai besoin d’aller prendre de l’air et de découvrir d’autres bibliothèques, car je me dis : à chacun son médicament !

Demain sera le jour du grand départ. Je compte me rendre à la succursale Carp. Stephen, un employé de la BPO, a récemment écrit un bon article sur le blog de la Bibliothèque Publique d’Ottawa où il mentionne cette succursale. Alors, je me suis dit pourquoi ne pas y aller.  Ensuite, étant à la succursale Carp, je déciderai quelle est la prochaine bibliothèque que je vais explorer. Aussi, à chaque bibliothèque je compte écrire dans mon journal intime comme je le fais en ce moment. Je vais y décrire mon parcours, mes découvertes et mes péripéties. Je vais mettre le plus de détail possible pour que je puisse me souvenir de mon voyage à vélo. Je voudrais pouvoir me relire dans quelques années, voire quand je serai à la retraite.
Je vais retourner chez moi pour continuer à me préparer pour mon voyage à vélo. J’habite seul dans un logement que je loue. Ce logement est situé à 200 mètres de la bibliothèque. La seule chose qui nous sépare, c’est le terrain de stationnement du complexe récréatif Ray Friel.
