[#chapter-five]
= Bibliothèque Publique d’Ottawa - Succursale Carp

[.text-right]
*Samedi 30 juillet 2016* – _10:50 - 26 degrés Celsius_

Je viens d’arriver à la succursale Carp. Tout au long du trajet à vélo pour arriver ici, j’ai dû me battre avec le doute. J’ai presque tout prévu pour mon voyage à vélo, mais je n’avais pas prévu que j’allais avoir autant de soucis qui allaient me passer par la tête. Je me disais que c’était dangereux de faire le voyage tout seul, que ça ne valait pas la peine, qu’une voiture pourrait me percuter, etc. Je n’avais pas prévu combattre toutes ces incertitudes-là. Le pire, c’est que ces doutes suscitent en moi de l’insécurité et cette dernière fait en sorte que je deviens angoissé. C’est comme si je me disais qu’il valait mieux que je reste chez nous. Je me suis aperçu que le doute sur la nécessité de mon voyage à vélo m’envahit parce que, parmi d’autres choses, j’ai peur de l’inconnu. Je crois que je me crée beaucoup trop de scénarios d’horreurs dans ma tête. Je me demande si les gens, par exemple Terry Fox, ont eu autant de doute ou ont dû faire face à autant de démons mentaux quand ils ont commencé leur voyage.

Pour me calmer, je vais décrire ma découverte… Car à chacun son médicament. Je suis à la succursale Carp de la Bibliothèque Publique d’Ottawa. Je me sens comme à la maison parce que cette succursale fait partie du réseau de la Bibliothèque Publique d’Ottawa, ce qui résulte en un décor similaire aux autres succursales de la BPO, la succursale Cumberland notamment, celle qui est tout près de chez moi. Le tapis, les couleurs des peintures choisies et les meubles sont pareils. Ils ont tous les mêmes éléments de décoration qui me sert de point de repère et qui me fait me sentir à mon aise pour circuler dans la bibliothèque.

En résumé, même si je ne suis pas à la succursale d’Orléans je me sens presque comme si j’y étais. Le décor fait en sorte que je me sens encore dans mon élément, comme si je n’avais pas quitté la ville d’Ottawa.

Mais, géographiquement, j’ai l’impression d'avoir quitté Ottawa parce que cette succursale est quand même éloignée de la ville. Parfois, on dirait que j’ai encore en tête le zonage de la ville d’Ottawa avant la fusion avec les municipalités même si ça fait quand même plus de 15 ans de cela. Le plus à l’ouest des bibliothèques auxquelles je me suis rendu, c’est celle de Beaverbrook qui est située dans l’arrondissement de Kanata. Et même Kanata, je la considère comme une ville qui est à l’extérieur de la ville d’Ottawa.
Pour poursuivre mon exercice de relaxation. Je vais décrire un meuble de rayonnage : un présentoir à revues. Un présentoir à revues est un meuble qui sert tout simplement à exposer des périodiques. Il y a 4 présentoirs à revues dans la section où je me trouve. Il y a deux types de tablettes dans ces présentoirs à revues : tablettes présentoirs et des tablettes horizontales. Les tablettes présentoirs du meuble sont en angle, ce qui permet de placer les magazines de façon à ce que l’on voie la couverture en premier. Chaque tablette présentoir est en métal et a un butoir. Ce dernier fait en sorte que les revues ne glissent pas et ne tombent pas par terre. En d’autres mots, un butoir est un dispositif d’arrêt. Le butoir sert aussi de manche ou de point d’appui servant à soulever la tablette parce qu’une tablette horizontale est dissimulée en dessous. La tablette présentoir est aussi appelée « porte escamotable » parce qu’on peut la soulever pour aller récupérer les anciennes parutions de revue. Pour récapituler, la tablette présentoir sert à montrer la plus récente parution d’une revue et la tablette horizontale sert de stockage pour les anciennes parutions. La tablette inférieure du meuble de rayonnage est à environ trois pouces du sol et il y a un socle longitudinal. Ce dernier sert à cacher le dessous du meuble de rayonnage autrement dit l’espace entre la tablette inférieure et le sol. Les deux côtés latéraux des présentoirs à revues sont en bois.

Je me sens détendu. À chacun son médicament. Je dois avouer que j’ai toujours trouvé ça difficile d’écrire dans un journal intime. Je deviens émotif, ce qui fait que je raconte mon histoire au fil de mes pensées, sans trop de structure. Une idée en amène une autre. Cela ne veut pas dire que je raconte l’histoire de façon chronologique.

Si je procède d’une manière chronologique, je vais relater mon parcours depuis mon lieu de résidence près de la succursale Orléans. J’ai pédalé jusqu’au terminus du centre d’achat d’Orléans parce que c’est là que je dois utiliser un transport en commun offert par la ville d’Ottawa pour me rendre vers Kanata. Les autobus du transport en commun de la ville d’Ottawa ont pour la plupart un support à vélo ayant la capacité de prendre au maximum deux vélos. C’est pratique comme idée d’avoir mis un support à vélo ! Ça m’a bien été utile. J’ai pris deux autobus pour me déposer le plus à l’ouest que possible de la ville d’Ottawa. Que dis-je ? Je suis toujours techniquement dans la ville Ottawa ! J’ai pris deux lignes d’autobus. Ensuite, je suis descendu à 9 :45 à l’arrêt du Centre Canadian Tire, là où les Sénateurs d’Ottawa, l’équipe locale de la Ligue nationale de hockey, jouent leurs matchs. De là, j’ai pédalé pour me rendre à la succursale Carp.

Ça m’a un peu irrité d’arriver au Centre Canadian Tire à 9 :45 du matin puisque j’avais prévu y être à 9 :30. Ensuite, j’avais prévu pédaler jusqu’à la succursale Carp pour y arriver à 10 :00, mais je suis arrivé à 10 :20 à cause du retard que j’ai eu en attendant le deuxième autobus qui devait me mener au Canadian Tire Centre. Je prévois passer encore un peu de temps dans cette succursale pour apprécier la bibliothèque. Mais je ne pourrai pas rester trop longtemps, je prévois rester tout au plus jusqu’à midi et demi parce que je m’aperçois que je n’aurai peut-être pas le temps de visiter deux autres bibliothèques avant 5 heures. J’avais prévu visiter 3 bibliothèques aujourd’hui. Je n’ai pas encore décidé à quelle bibliothèque ou succursale me rendre. Je me donne encore 30 minutes avant de me décider. Enfin, peut-être même que c’est quand j’enfourcherai mon vélo que je prendrai la décision finale.

Quelque chose d’important à noter à la succursale Carp, c’est la statue à l’extérieur, tout près de la porte d’entrée de la bibliothèque. Je crois qu’elle représente un père qui lit un livre à sa fille. Tous deux sont assis sur le même banc. L’ambiance semble interactive comme si la fille posait une question, ou bien s’étonnait du déroulement de l’histoire que son père lui raconte. C’est un peu comme si la statue me disait, avant même que j’ouvre la porte pour entrer à la succursale Carp, que les livres qui y sont proposés sont remplis d’histoires fascinantes qui me feront me poser des questions, me découvrir, me réaliser, voire me faire tisser un lien familial avec autrui.

La statue m’amène à me souvenir quand et pourquoi j’ai commencé à aimer les bibliothèques. En fait, il y a deux raisons. Premièrement, je suis arrivé au Canada en 1992, en début d’année, une semaine après le jour de l’an. Je me rappelle qu’il neigeait cette journée-là, il était aux alentours de 6 heures du soir. Ce n’était pas la neige qui m’étonnait, c’est qu’il faisait nuit. Venant d’Haïti, je m’étonnais qu’il fasse nuit aussi tôt. Ensuite, de Mirabel, ma famille a été s’héberger temporairement à Côte-des-Neiges chez mon oncle, le frère de mon père. Le deuxième jour, mon cousin, le fils de mon oncle, m’a invité à aller à la bibliothèque de Côte-des-Neiges. Alors, nous sommes sortis. Il y avait un bouchon de circulation sur une des rues qu’on a empruntées. Toujours en marchant pour me rendre à la bibliothèque, j’ai même vu des camions de pompiers et une ambulance. Quand je suis arrivé à la bibliothèque de Côte-des-Neiges, à l’époque, je l’ai trouvée vaste. J’ai trouvé qu’il y avait une tonne de livres. Beaucoup de gens circulaient librement à la bibliothèque, je pouvais poser des questions à la bibliothécaire et au préposé. Tous les employés étaient là pour m’aider ! Ils me prenaient au sérieux quand je leur posais une question même à l’âge que j’avais à l’époque. C’était génial. Que de beaux souvenirs. C’était la première fois que je voyais une bibliothèque. Alors, depuis ce jour, j’aime vraiment les bibliothèques. Ça me rappelle ma venue au Canada. Je me souviens plus particulièrement des nouveautés que j’ai vues à ce moment de ma vie, surtout les camions de pompiers, l’ambulance et la bibliothèque. Dans cet ordre spécifiquement.

L’autre raison qui m’a poussé à m’intéresser aux bibliothèques est la détente. Je m’explique : quelque temps après mon arrivée au Canada, j’étais à l’école primaire à Gatineau. Je devais avoir 8 ans. J’avais ce que ma professeure nomma des « troubles d’anxiété ». La professeure en parla avec mes parents pour leur suggérer des plans d’action. Au cours de la conversation, mes parents entendirent quelque chose qu’ils ne souhaitaient pas entendre : « travailleuse sociale ». Mes parents avaient en horreur d’avoir affaire avec une « travailleuse sociale ». Je ne sais pas pourquoi. Mais, je me doute que c’est à cause des rumeurs qu’ils ont entendu. Peu importe, mes parents me disaient qui dit « travailleuse sociale », dit « DPJ », « psychologue », « vie gâchée », « drogues », etc.

Je ne savais pas ce que c’était des troubles d’anxiété. Tout ce que je savais c’est que j’avais plusieurs sensations que je ne comprenais pas, j’avais des sueurs sur le front, je me sentais étourdi comme si j’allais m’évanouir, j’avais d’innombrables spasmes musculaires et j’avais tous ces symptômes même quand je me sentais calme. Parfois, un symptôme pouvait venir seul et d’autres fois je pouvais ressentir plusieurs symptômes en même temps. Concernant les spasmes, ce n’était pas nécessairement perceptible à moins que quelqu’un m’ait touché là où se produisaient les tremblements. Mais, j’en avais beaucoup. J’étais souvent déconcentré et je me demandais ce qui se passait à l’intérieur de moi.

Comme d’habitude, le coupable était moi-même, selon mon père. Il me disait que je souffre de troubles d’anxiété parce que j’étais une « grammaire française ». C’est une expression péjorative qu’il avait créée pour désigner quelqu’un qui manque de fermeté ou d’assurance. Selon lui, la langue française a beaucoup d’exceptions et parfois on se demande si un nom est féminin ou masculin. Ce qui fait qu’on a souvent un doute quand on veut s’exprimer. Comparativement au créole ou à l’anglais qui sont plus simples ou plus directs, donc plus rapide à maîtriser et à utiliser pour s’exprimer, à son avis. Franchement, des fois je trouvais que les expressions qu’il inventait n’avaient pas de sens.

En résumé, mon père n’avait rien contre la langue française, mais il se servait de cette expression pour dire que je ne sais pas ce que je veux, que je pense trop avant d’agir, que je suis trop hésitant. Qu’un homme doit être ferme. C’est pour ça que j’ai des troubles d’anxiété. C’est mon corps qui me le dit. C’était le pronostic de mon père.

Mes parents ne faisaient pas confiance aux psychologues non plus, ils disaient qu’ils étaient pires qu’un hougan et qu’ils allaient me gaver de médicaments. Un hougan est un chef spirituel de la religion vaudoue.  Alors, ma mère m’a dit que, lors de mes crises d’angoisses, je devais me concentrer sur un objet quelconque.

En fait, elle m’a donné plusieurs choix, comme de me répéter plusieurs fois le nom de « Jésus », ou alors de réciter plusieurs fois le « psaume 21 » ou de me concentrer sur quelque chose de positif, qui me fait du bien. Je ne savais pas trop pourquoi, mais me servir des bibliothèques comme moyen de relaxation fonctionnait.

Depuis lors, quand je me sens agité ou angoissé, je décris une bibliothèque, que ce soit en tentant de décrire tout ce que je sais de la bibliothèque ou spécifiquement en décrivant des objets de la bibliothèque. Tout cela dans le but de retrouver mon calme. Le temps de description varie entre 30 secondes et trois minutes. D’habitude, je fais l’exercice de description d’une bibliothèque de façon mentale ou en chuchotant. Mais puisque je m’étais dit que je devais écrire ce que je pense dans mon journal, j’obéis. Je dois dire que j’écris moins de choses en 30 secondes que si je faisais l’exercice mentalement pour la même durée. Mais j’ai le même résultat, je retrouve mon calme. C’est ce qui importe. Je ne suis pas obligé de me rendre à la bibliothèque pour faire mon exercice de relaxation, mais je me sens plus calme plus rapidement si j’y suis.

Donc, quand je dis « à chacun son médicament » c’est pour dire que chacun a un remède qui lui est adapté, une solution qui lui est propre pour faire face à un problème. Mes parents ne croyaient pas beaucoup au remède chimique : les pilules que prescrivent les médecins. Ils préféraient les remèdes naturels, la prière et la force du mental. Jusqu’à présent, souvent après une journée au travail, je me rends à la bibliothèque pour me détendre, lire un livre, dessiner, jouer à des jeux vidéo, participer à un atelier, continuer à faire ma généalogie, etc.
