[#chapter-six]
= Bibliothèque d’Arnprior

[.text-right]
*Samedi 30 juillet 2016* - _14:50 – 32 degrés Celsius_

Bon sang que c’était long la route! J’ai considéré rebrousser chemin à plusieurs reprises pour retourner chez moi à Ottawa. Google Maps avait prévu un trajet en bicyclette de 1h39 minutes pour arriver à Amprior. 1h39 minutes… Ce n’est pas réaliste du tout! Les serveurs de Google doivent connaitre un bogue pour calculer un trajet de 1h39. C’était vraiment long le chemin pour arriver à Amprior. Je n’en reviens pas!

Bon, il faut que je change de disque parce que rien qu’à penser à ma mésaventure, ma tête commence à me faire mal, je sens la colère monter et ce n’est pas bon pour ma santé mentale.
Dès que je suis arrivé à la bibliothèque, je me suis senti soulagé. Ensuite, j’essayais de deviner où était située une table d’étude individuelle où je pourrais écrire. J’en ai aperçu un au fond vers les grandes fenêtres. Maintenant, il fallait que je fasse un exercice de relaxation: que je décrive la bibliothèque pour que je retrouve mes bonnes habitudes… Car à chacun son médicament!

À bien y penser, je vais prendre le temps de faire le tour de la bibliothèque. Ensuite, je vais retourner à mon journal pour décrire ce que j’ai vu dans cet établissement. J’ai oublié de mentionner qu’il faut aussi que j’aille vérifier si j’ai bien cadenassé ma bicyclette.

[.text-center]
…

Oh la belle bibliothèque ! Comme elle est élégante, cette bibliothèque, et bien soignée aussi! Je suis à la bibliothèque publique d’Arnprior. Je voulais aussi préciser que la ville s’appelle Arnprior non Amprior. J’ai dû être quelque peu dyslexique, en lisant les panneaux de signalisation sur le long de la route. Quand je suis stressé ou préoccupé, je n’ai pas le temps de m’attarder aux détails ou de voir la beauté des choses. Si je reviens à mon appréciation de la bibliothèque, je dirais que c’est la crème de la crème. Je ne m’attendais pas à voir une bibliothèque aussi splendide. C’est comme si j’avais trouvé une oasis au milieu du désert.

Tout le long du trajet à bicyclette, je cherchais un endroit qui serait à l’ombre et qui me ressourcerait spirituellement. Arrivé à un certain point, malgré que la carte géographique que j’ai avec moi m’indiquait que la bibliothèque la plus proche de l’endroit où je me situais se trouvait à Arnprior, j’espérais au fond de moi que la carte se trompe: qu’une municipalité que je traverse ait récemment inauguré une bibliothèque et que Google Maps n’a pas encore fait la mise à jour de cette information. Mais je n’ai pas vu d’autres panneaux de signalisation indiquant une bibliothèque municipale.
Comment décrire la bibliothèque publique d’Arnprior? Je ne sais pas par où commencer tellement il y a de points à souligner. OK, je sais! Je vais commencer par la luminosité. Je crois que c’est la bibliothèque la mieux éclairée, la plus lumineuse à laquelle je suis allé. Une des façades du bâtiment de la bibliothèque est composée de plusieurs grandes fenêtres. Il y a aussi quelques miroirs, qui amplifient l’effet des grandes fenêtres, en agissant comme réflecteurs pour diffuser la lumière extérieure à l’intérieur de la bibliothèque. C’est comme si l’architecte de la bibliothèque avait voulu favoriser l’éclairage naturel extérieur.

Ensuite, j’aime les œuvres d’art exposées dans une bibliothèque. L’art me fait rêver, ça me fait réfléchir. Quand je fais un devoir à la bibliothèque et que je n’arrive pas à comprendre ou à résoudre un problème, que ce soit en mathématique ou en toute autre matière, je me tourne souvent vers un tableau ou une œuvre d’art de la bibliothèque. L’art me fait voir les choses sous un autre angle.

C’est comme si l’auteur de l’œuvre artistique avait voulu me divulguer une information connue de tous, mais pour la rendre plus appréciable, il a décidé de le dévoiler sur un autre angle. En parlant d’art, à la bibliothèque d’Arnprior, la bibliothécaire Karen s’implique à fond! Elle a confectionné quelques œuvres artisanales qu’elle a mises dans la bibliothèque. C’est la préposée au comptoir de prêt qui m’a dit en anglais que Karen les a faites et elle m’a aussi dit que la bibliothécaire anime un atelier. Elle s’implique vraiment, cette femme!

Aussi, j’aime la signalétique, je la trouve créative. La signalétique est là pour aider les usagers à s’orienter dans la bibliothèque. Il y a différent type de signalétique dans une bibliothèque, mais je vais me concentrer sur la signalétique adoptée pour un meuble de rayonnage contenant des livres. Sur ce meuble de rayonnage, on affiche sur les côtés latéraux de l’information concernant la plage des côtes que contient ce meuble. Si je cherche un livre de philosophie qui débute avec la cote 100, alors je vais me diriger au meuble de rayonnage qui a un panneau de signalisation latérale qui indique que ce meuble contient des livres ayant les côtes de 100 à 200. Les cotes suivent généralement le système de classification Dewey. Pour simplifier ce qu’est un système de classification, je pourrais dire qu’à la base, il y a différentes façons de classifier un livre. On peut le faire par sujet, par nom d’auteur, par date de parution, etc. Le système de classification Dewey est le plus répandu à travers le monde dans les bibliothèques publiques. Ce système catégorise les livres en dix classes, 100 divisions, 1000 sections et plusieurs sous-sections. Chacune des classes, des divisions, des sections et des sous-sections a un nombre qui lui correspond. Une classe est en quelque sorte un sujet d’ordre général, la religion par exemple, et cette classe est associée au nombre 100. Je ne vais pas rentrer trop dans les détails de ce système de classification.

À la bibliothèque publique d’Arnprior, on use d’imagination pour donner des indices aux lecteurs afin de les aider à deviner quels sont les sujets des monographies qui se trouvent dans ce meuble de rayonnage. Par exemple, pour le meuble de rayonnage qui contient des livres de cuisine, il y a un panneau de signalisation latérale qui indique que ce meuble contient des livres ayant les côtes de 641 à 648. Je parle de panneau parce que c’est d’habitude des panneaux en métal que je vois dans des bibliothèques, mais ceux de la bibliothèque Arnprior sont en fait une feuille de papier. Ensuite, en dessous, il y a un autre panneau de signalisation recouvert de plastique qui est en fait un collage. Ce dernier a en toile de fond d’une feuille 8 et demie par 11 une photocopie d’une recette de cuisine, en l’occurrence, le «Cinnamon Pudding» sur lequel on a superposé le mot «Cooking» pour indiquer le sujet qu’on est propice à rencontrer dans ce rayonnage. Ensuite, on a aussi superposé au milieu de la feuille l’image d’un fouet à blanc, un ustensile de cuisine qui sert à battre les œufs. Un autre exemple de collage est fait pour les livres dont la côte est entre 759 et 795. Une partition de musique est en toile de fond. Il y a aussi une image d’une caméra professionnelle, enfin il y a les mots «Arts» et «Music» pour signaler que dans ce meuble de rayonnage, on trouvera des livres reliés aux arts et à la musique, vous l’aurez compris.

Donc, la signalétique adoptée pour les meubles de rayonnages, du moins au premier étage, comporte deux panneaux: le premier indique quelles plages de côtes de livre se trouvent dans ce meuble et un panneau qui indique, par un collage, quels sujets contient ce meuble contient. Le collage, pour faire un rappel, est composé d’un ou plusieurs mots et d’images superposées sur une photocopie d’un document. De cette façon, les usagers de la bibliothèque peuvent savoir quels sujets se trouvent dans cette section du meuble de rayonnage rapidement. La bibliothèque a deux étages. Le rez-de-chaussée et le sous-sol. Pour les personnes à mobilité réduite, un ascenseur est disponible. Dans le sous-sol de la bibliothèque, ce que j’ai apprécié le plus, c’est le fait d’avoir un babillard sur lequel les gens peuvent apposer leur suggestion de lecture pour l’été. Sur le babillard, les gens épinglent une sandale en papier d’une largeur d’environ 2 pouces et d’une longueur d’environ 5 pouces sur laquelle on écrit les suggestions de lecture. Je trouve ça mignon! La prochaine fois que je trouverai une boîte à suggestion dans une bibliothèque, je vais écrire sur un petit bout de papier cette idée et ensuite l’y insérer.

Bon maintenant que je me suis ressaisi, je peux dorénavant me mettre à décrire mon trajet. Je trouve que le trajet a été excessivement long pour arriver ici. Je n’avais pas prévu cela.

Il fait au moins 32 degrés Celsius et le ciel est dégagé, ce qui fait que le soleil me tapait constamment sur la tête. Le fait qu’il fait aussi chaud, ça a ralenti ma cadence et, à vrai dire, je ne pédalais vraiment pas vite (entre 14 et 18 km/h, c’est ce que disait mon odomètre à vélo). Il faut ajouter le fait que je me suis arrêté souvent pour trois raisons. Premièrement, c’était pour prendre une gorgée d’eau. Deuxièmement, c’était pour sortir d’une des valises accrochées à mon vélo mon cellulaire, dans le but d’utiliser une application qui me sert à dicter mes notes comme un enregistreur numérique, afin de me donner des pistes d’écriture lorsque j’écrirais dans mon journal intime à la prochaine bibliothèque qui croiserait ma route. Troisièmement, c’était pour juger si ce n’était pas mieux de retourner à la maison…

[.text-center]
…

Ça m’a pris près de 2 heures et demie pour arriver ici et il faisait très chaud et le soleil me tapait sur la tête lors du trajet entre la succursale de Carp et la bibliothèque d’Arnprior. Comme s’il me tapait pour me faire savoir à quel point je ne suis pas intelligent.

Je viens de remarquer que j’ai de la difficulté à me souvenir du paysage tellement j’ai été préoccupé par mes problèmes. J’ai fait plusieurs kilomètres et je ne me souviens pas du paysage. C’est sûrement parce qu’il n’y avait rien de très beau. Tout de go, ce que je me rappelle, c’est d’un serpent mort sur la route et du cruel manque de panneaux de signalisation indiquant une bibliothèque municipale. J’ai vu aussi plusieurs corbeaux, des rapaces qui s’envolaient autour de moi pour me dire que ma carcasse ne vaut rien sauf pour eux.

Pour revenir au serpent, il a sans doute été écrasé par les roues d’un véhicule routier. Je déduis cela par la trace rouge de pneu que j’ai vue à côté. Le symbolisme du serpent me rappelait le serpent de la genèse dans la bible. Celui qui est venu inciter nos péchés, nos imperfections. J’ai été dupé! C’est pour ça que je me suis endetté de 2000$.

Ça m’arrive encore une fois ! J’ai des angoisses et je me sens en colère. Oh, mon Dieu, pourquoi est-ce que je me suis encore endetté? Comment est-ce que j’ai pu faire cela? Je me remémore un événement qui est survenu plusieurs années auparavant. Je me rappelle d’un de mes potes, Steve. On habitait le quartier de Vanier à Ottawa et je devais avoir 16 ans. On jouait souvent au basket ensemble. Il était plus fort à ce sport et, côté habit, il était plus swag que moi. Il avait tout à envier: son visage d’ange ou son «baby face» comme on disait à l’époque et le fait qu’il était ami avec tout le monde. Ensuite, j’ai déménagé et je l’ai perdu de vue pendant environ trois ans, jusqu’au jour où je l’ai vu paraitre dans le journal télévisé parce qu’il s’était fait arrêter par les forces de l’ordre pour un vol à main armée. Quand je suis retourné dans mon ancien quartier pour savoir ce qui s’était passé, chaque personne que je connaissais à l’époque que j’habitais le quartier m’a dit qu’elle ne savait rien. Quand je parle de quartier, je veux dire précisément une rangée de logements communautaires, là où j’habitais il y a quelques années de cela avec mes parents.

Comme ça faisait longtemps que les gens ne m’ont pas vu dans ce quartier, ils ont dû penser que je travaillais pour la police. Mais, quoi qu’il en soit, je me suis démené parce que je me souciais de ce qui lui était arrivé. On m’a expliqué qu’il avait commis le vol à main armée parce qu’un caïd lui avait que s’il ne remboursait pas les 6000$ empruntés le lendemain, il mourrait le jour après demain. À ce moment-là, j’ai constaté à quel point les dettes et les dates d’échéances peuvent changer les gens. C’est fou.

Le fait de me rappeler de l’histoire de Steve m’a fait constater que je me fais beaucoup trop de scénarios d’horreurs!

Moi qui avais des projets, voilà que je m’endette encore plus. Mes projets sont tombés à l’eau ou, à tout le moins, ils vont prendre un sacré coup de retard. Qu’est-ce que mes collègues vont penser de moi?
Il faut absolument que je raconte le pétrin dans lequel je suis. Ça va peut-être sortir toute croche dans mon journal intime, mais je dois l’écrire! Comme dit l’adage, je suis aussi malade que mes secrets. Et mon secret c’est que j’ai échoué à un cours d’été. Je ne pourrai pas commencer ma maîtrise cet automne pour devenir bibliothécaire. On m’a retardé d’un an. Un an, c’est énorme!

Je sens la pression augmenter, il faut que je me calme. Je vais compter jusqu’à 10. Succursale Carlingwood de la BPO, Bibliothèque Lucien-Lalonde, bibliothèque Manise-Morin, succursale BlackBurn Hamlet de la BPO, succursale Orléans de la BPO, succursale Gloucester de la BPO, bibliothèque de Cantley, succursale Rideau de la BPO, succursale Alta-Vista de la BPO et succursale Sunnyside de la BPO.
Je n’aime pas compter jusqu’à 10 juste pour compter jusqu’à 10. Je préfère avoir de bonnes sensations dans la tête quand je compte. À chacun son médicament!

Alors, si je procède d’une manière chronologique, c’est jeudi dernier, avant-hier quoi, que j’ai consulté mes notes pour les cours que je suivais cet été. Je n’ai pas obtenu la note de passage. Beaucoup de conséquences résulteront de l’échec que j’ai obtenu. Par exemple, je devrai reprendre le cours ou m’inscrire à un autre. De plus, je pensais déménager à Montréal dans quelques semaines pour pouvoir commencer ma maîtrise. Là, je suis foutu: je ne pourrai pas commencer ma maîtrise parce que je n’aurai pas mon baccalauréat en sciences sociales cet été. Tant et aussi longtemps que je n’aurais pas terminé ce cours, je ne pourrai pas avancer.

De plus, même si je suis un cours à l’automne 2016 à l’université d’Ottawa et que je le valide, je ne pourrai pas commencer le programme de maîtrise en sciences de l’information à la session d’hiver qui débute en janvier 2017, car on ne peut pas commencer cette maîtrise à l’Université de Montréal à la session d’hiver: il faut absolument débuter à la session d’automne. Pour résumer, même si je reprends ce cours cet automne à l’université d’Ottawa, je devrai absolument attendre l’année prochaine, soit en septembre 2017 pour commencer ma maîtrise.

[.text-center]
…

Pour changer de sujet et en revenir au voyage à vélo, je n’ai pas une bonne bicyclette enfin une qui est adaptée pour mon voyage. J’ai un Nakamura Royal de l’année, mais d’après le mécanicien qui l’a mis au point pour le voyage, mon vélo n’est pas fait pour ce type de trajet. C’est un vélo hybride bas de gamme. De plus, c’est la première fois que je surchargeais ma bicyclette avec autant de stock. C’est aussi la première fois que je fais un voyage à vélo pour aller de bibliothèque en bibliothèque. Donc, je crois que la qualité de mon vélo, son poids et mon inexpérience  sont les raisons pour lesquelles je n’ai pas pu pédaler aussi vite que je l’avais prévu.

Je réalise que la bibliothèque fermera dans 20 minutes et que, sur la carte géographique, il n’y a pas d’autres bibliothèques qui sont encore ouvertes et que j’aurais le temps d’atteindre en bicyclette avant la fermeture. Alors, je vais reprendre la route pour me diriger vers l’ouest pour m’arrêter à Logos Park parce qu’il y a un terrain de camping là-bas. Je pourrai y passer la nuit. Qui plus est, demain matin, je pourrai aller à l’église. Logos Park est un terrain de camping chrétien et il y a un culte en forêt qui a lieu tous les dimanches pendant la période estivale. Ensuite, je me dirigerai vers la ville de Pembroke.
La bibliothèque Arnprior est le troisième arrêt dans mon voyage. Je dis troisième, parce que je considère la succursale de Cumberland comme la première bibliothèque que j’ai vue au cours de mon voyage. J’aime bien inclure la journée de préparation d’un voyage comme faisant partie du voyage.

La bibliothèque d’Arnprior est vraiment chouette! Non, à bien y penser, je retire ce que j’ai dit auparavant quand je disais que j’aurais voulu rebrousser chemin et retourner à Ottawa. Ça vaut la peine de partir à l’aventure, de faire un voyage à vélo pour aller explorer d’autres bibliothèques. Quand je vois à quel point cette bibliothèque est formidable que ce soit le personnel, les livres, les arts, le design, la luminosité, la signalétique, etc. Je suis certain de voir d’autres belles bibliothèques dans mon parcours vers le nord-ouest. J’ai planifié mon trajet avec Google Maps, en fait j’ai imprimé une carte géographique m’indiquant toutes les bibliothèques qui se trouvent dans chaque ville au nord-ouest d’Ottawa jusqu’à North Bay. Au jour le jour, je vais décider à quelles bibliothèques je participerai.
J’utilise le verbe «participer» au lieu du verbe «visiter». Je trouve que le verbe «visiter» a une connotation plus passive. Quand je dis que je vais participer dans une bibliothèque, c’est comme si ma présence était importante. Je participe en étant présent, en posant des questions au personnel, en m’inscrivant à un atelier qu’offre la bibliothèque, en faisant des suggestions d’achat de livres, en utilisant les services, en visitant le site internet, en lisant le dernier procès-verbal de la BPO, en essayant de comprendre les rapports budgétaires… Il y a plein de choix, plusieurs manières de participer à la bibliothèque. Comme ma mère me dit toujours : «tout est intéressant, il suffit d’être intéressé».
