[#chapter-seven]
= Bibliothèque publique de la région de Whitewater : Succursale Cobden

[.text-right]
*Dimanche 31 juillet 2016* - _13:00 – 32 degrés Celsius_

En ce moment, il y a des nuages qui cachent le soleil, ce qui est bien parce que la température est supportable. Comme je suis assis sur un banc public, je ne suis pas à mon aise alors je ne crois pas que je vais écrire beaucoup. D’emblée, je dois dire que je trouve que j’ai la mèche courte, que je me fâche pour un rien. C’est la succursale Cobden qui m’a fait remarquer ce trait de caractère. Il faisait extrêmement chaud sur la route pour arriver ici. On dirait que la chaleur et surtout le soleil qui me tapait sur la tête pendant mon voyage pour arriver ici aient augmenté mes craintes les plus profondes.

Pour me situer, je suis présentement à Cobden au coin de la rue Main et de la rue Gould. Je suis assis sur un banc à environ 80 mètres de ce qu’on appelle en anglais la «Little Free Library» (LFL). On la nomme de plusieurs manières en français, par exemple la «Bibliothèque d’ Échange» (BE) ou la «Petite Bibliothèque Libre» (PBL) ou la «Petite Bibliothèque Communautaire» (PBC). Le concept de la PBC est simple: c’est tout d’abord une bibliothèque, dans le sens de «meuble dans lequel sont rangés des livres», que le propriétaire confectionne généralement lui-même et qu’il place au-devant de sa maison. Ensuite, le principe est qu’un passant peut prendre un livre gratuitement, à condition qu’il laisse lui aussi un livre dans la Petite Bibliothèque Communautaire. Je ne m’attendais pas à voir une PBC et encore moins de ce type. J’espérais la manifestation d’une bibliothèque publique et je n’en ai pas trouvé une qui soit ouverte. Par contre, la ville a mis à la disposition de tous une Petite Bibliothèque Communautaire. Je crois que c’est la ville qui en est le propriétaire parce que la PBC est située sur le terrain de l’Hôtel de Ville de Cobden.

C’est original et simple la manière dont la PBC a été confectionnée. On a pris 4 troncs d’arbre d’environ 7 pieds de hauteur et chaque tronc a été planté au sol, l’un à côté de l’autre, de façon à former un cercle. Chaque tronc d’arbre porte encore leur écorce et est de diamètre semblable. Aussi, dans chacun des troncs, il a deux ou trois fentes rectangulaires dans lesquelles on a inséré une boîte qui a une portière. Les boîtes ont cinq côtés faits en bois, mais le sixième côté est une portière que les gens peuvent ouvrir pour prendre un livre. Pour la portière, on a encadré une feuille de plastique transparent de manière à ressembler à une vitrine pour que les passants puissent voir les titres des livres sans nécessairement avoir besoin d’ouvrir la portière.

[.text-center]
…

Je veux profiter pleinement de mes vacances, avoir le moins de soucis possible et m’amuser au max, mais je trouve que c’est difficile de me sentir heureux quand j’ai des problèmes qui me préoccupent. Il faut absolument que je reparle de ce qui me tracasse.

J’ai eu un échec à mon cours de comptabilité. Je sais en mon for intérieur que j’aurais pu faire mieux et réussir ce cours. J’avais suivi ce cours au choix parce que je me disais que ce serait un bonus pour ma carrière. Un «cours au choix» est un terme qui désigne un cours qui ne fait pas partie de l’ensemble des cours offerts dans mon programme d’étude. Je suis en train de faire mon bac en sciences sociales et il y a un cours dans le cadre du certificat en gestion qui m’intéressait, donc je l’ai sélectionné pour pouvoir faire une demande auprès de ma faculté pour l’intégrer dans mon programme par la suite.

Je regrette d’avoir suivi le cours de comptabilité. Si j’avais su que la charge d’étude serait aussi lourde, je n’aurais pas suivi ce cours. Je ne m’y connais pas en comptabilité et j’ai voulu m’initier aux sciences comptables, alors j’ai pris ce cours dans un programme autre que le mien. Les autres élèves qui sont déjà dans un programme de gestion ou de comptabilité ont eu la compréhension plus facile que moi, en tout cas c’est la conclusion à laquelle je suis venu après avoir constaté la rapidité avec laquelle il finissait un soi-disant simple exercice en classe. Je travaille à temps plein et j’ai suivi 2 cours d’été. Un dans mon programme d’étude et un cours au choix. J’en ai validé un, mais l’autre je l’ai échoué. Je misais sur mon examen final pour remonter ma moyenne générale pour ce cours, mais l’examen final était plus difficile que je l’aurais cru. Il va falloir que je reprenne le cours de comptabilité ou m’inscrire à un autre cours pour pouvoir compléter mon bac.

Depuis trois ans, je travaille à temps plein et j’étudie à temps partiel en suivant un à trois cours par session. Je m’étais inscrit au programme de prêts et bourses pour mon diplôme collégial et pour la première année de mon bac. Ensuite, je me suis mis à travailler à temps plein pour rembourser les prêts et bourses parce que je commençais à avoir des cauchemars quand je pense à ma dette d’étude. Je n’avais jamais suivi plus qu’un cours en été. J’ai suivi deux cours parce que je voulais en finir le plus rapidement possible afin d’avoir mon bac. Il y a un moment dans la vie où l'on a hâte de passer à une autre étape. Ça, c’est le moment où j’en suis rendu. Je voulais commencer ma maîtrise à l’Université de Montréal en septembre 2016 non en septembre 2017. De cette manière, je pourrais entrer à la maîtrise ce septembre à l’Université de Montréal. Je veux déménager et découvrir encore plus de bibliothèques et surtout y participer. On dirait qu’avec l’âge rester dans un même endroit me fatigue. Voir les mêmes personnes et prendre le même trajet d’autobus. J’ai voulu déménager dans une autre ville juste pour changer d’air. J’aime Ottawa, mais je voudrais quand même découvrir d’autres lieux.

J’ai été admis conditionnellement à l’Université de Montréal pour faire ma maîtrise en sciences de l’information, ce qui veut dire que si je passe mes deux cours, je serai accepté à la maîtrise pour devenir bibliothécaire. J’ai demandé un transfert au travail pour déménager à la compagnie sœur à Montréal. Je devais commencer dans environ 6 semaines. Les vacances que j’ai prises, je les ai accumulées. Je voulais prendre environ une semaine maintenant et une semaine avant mon transfert en début septembre.

Où j’en suis dans ma vie de 33 ans? J’aurais voulu commencer tout de suite ma maîtrise. Je rêve depuis longtemps de devenir bibliothécaire. Je suis fier que ce soit moi qui aie choisi ce métier. Je n’ai pas été influencé par mes amis ou forcé par mes parents de choisir ce métier. Avoir le choix c’est de se sentir libre comme je dis. Pour revenir à mon lieu de travail, j’ai dit à tout le monde que je déménagerais bientôt. Mes collègues de travail sont sûrement en train de me préparer une carte de départ, voire une fête surprise pour ma dernière semaine de travail à Ottawa qui aura lieu dans quelques semaines. Là, il va falloir qu’ils annulent tout. Le seul point positif dans tout ça, c’est que je n’avais pas encore signé mon bail pour le nouvel appartement que j’avais trouvé à Montréal.

Concernant la dette de 2000$, elle représente le montant approximatif des frais de scolarité. Ces frais représentent le montant que j’ai à payer pour suivre les cours qui sont inscrits à mon horaire. Je n’ai pas encore terminé de payer mes frais de scolarité pour la session d’été. Il me reste qu’une toute petite partie que je compte payer lors de mon prochain chèque de paie. J’ai suivi deux cours et j’en ai validé un ce qui fait que j’ai au moins la moitié des frais de scolarité qui a bien été utilisée. L’école, c’est un investissement financier pour moi. M’endetter pour pouvoir payer mes cours, quand je sais que j’obtiendrai un diplôme à la fin, est pour moi une dette positive, mais si j’échoue un cours, il faut que je repaye ce cours. Cela fait que c’est comme si la première fois que j’ai payé le cours, l’argent avait été jeté à la poubelle.

J’ai oublié de mentionner mon parcours alors je vais le raconter. Hier, après avoir été à la bibliothèque d’Arnprior, je suis allé camper à Serenity Hills. C’est un terrain de camping situé à mi-chemin entre Arnprior et Logos Park. Je n’ai pas pu me rendre à Logos Park parce que le soleil allait se coucher et je n’aime pas monter une tente quand il fait nuit. Alors je suis allé au terrain de camping le plus proche de l’endroit où je me situais.

Ce matin, au terrain de camping de Serenity Hills, j’ai bavardé avec un voisin. Je lui ai dit que j’allais à Pembroke et que je tente de visiter le plus de bibliothèques possible. Il m’a dit que puisque je me dirige vers Pembroke, il y a une bibliothèque à Cobden et que cette ville n’est pas trop loin de Logos Park. Elle sera ouverte jusqu’à 13 heures aujourd’hui. J’étais tellement content de la nouvelle parce que je ne croyais pas qu’il y avait une bibliothèque qui serait ouverte le dimanche dans les environs. Mais là, j’avais un dilemme, si j’allais à l’église, je n’aurais pas le temps de participer à la bibliothèque. C’était plus fort que moi, j’ai choisi de ne pas aller à l’église parce que de toute façon je me suis dit que je pourrais sûrement trouver une église à Pembroke qui a un culte le dimanche soir. Alors je suis parti pour Cobden.

Je me suis quand même arrêté à Logos Park, non pas pour aller à l’église, mais pour remplir d’eau mes deux gourdes parce qu’il faisait très chaud. Un personnel du terrain m’a offert deux bouteilles d’eau quand il a vu que je remplissais mes gourdes à un robinet situé à l’extérieur d’une vieille bâtisse. En fait, maintenant que j’y pense, je ne sais pas si l’eau du robinet était potable ou non, mais j’avais tellement soif que j’en ai bu. Logos Park a, dans l’entrée, l’architecture d’une arche qui m’intriguait beaucoup. C’était la première fois que je voyais une arche. On aurait dit un bungalow dans un bateau. Mais, je ne me suis pas attardé au terrain de camping, je voulais arriver le plus rapidement que possible à la bibliothèque publique de Cobden.

J’étais très excité en arrivant à Cobden. J’y suis arrivé vers 12:10 PM. Je ne savais pas où était la bibliothèque précisément. Sur la carte géographique que j’avais apportée, je n’avais pas indiqué cette bibliothèque (sans doute parce que je me doutais qu’elle serait fermée). Aussi, j’avais envisagé de me rendre à Pembroke par un autre chemin, en passant par le village de Beachburg, parce que je n’aime pas circuler à vélo sur l’autoroute. Si j’y suis obligé, ça va, mais si je peux l’éviter je prends un autre chemin.

Pour poursuivre mon histoire, je suis arrivé à Cobden par l’autoroute 17, je n’ai pas remarqué un panneau de signalisation routière indiquant la présence d’une bibliothèque municipale. Jusqu’à présent en Amérique du Nord, j’ai vu trois types de panneaux de signalisation qui indiquent la présence d’une bibliothèque dans les environs. Premièrement, il y a celui nommé le National Library Symbol adopté par l’American Library Association (ALA) dans les années 1980. C’est le panneau de signalisation le plus commun. Moi je l’appelle le I-8 parce que c’est la manière dont l’illustration de ce panneau a été identifiée dans le Manual on Uniform Traffic Control Devices, publié par le Fédéral Highway Administration (FHA), aux États-Unis d'Amérique. Le National Library Symbol est le pictogramme d’une personne qui lit un livre. Deuxièmement, il y a le panneau de signalisation I-370-2 qu’on retrouve surtout au Québec, c’est le pictogramme d’un bâtiment qui contient 5 livres. Ces deux panneaux de signalisation routière, le I-8 et le I-370-2, symbolisent la présence d’une bibliothèque dans les environs. Troisièmement, on peut voir un panneau de signalisation simplement avec le mot bibliothèque inscrit dessus. Ces trois panneaux sont souvent accompagnés d’un panonceau de direction. Ce dernier pointe la direction où se trouve la bibliothèque et indique aussi le nombre de kilomètres à parcourir pour l’atteindre. Il existe aussi d’autres types de panneaux de signalisation qui indiquent la présence d’une bibliothèque, mais j’ai nommé ceux que j’ai déjà vus.

Encore une fois, j’ai coupé le déroulement de mon histoire. Pour poursuivre, je n’ai pas vu de panneaux de signalisation, arrivé à Cobden. Alors j’ai suivi mon instinct: j’ai emprunté la rue Main et j’ai demandé à un passant quelles étaient les directions pour la bibliothèque. On m’a indiqué qu’elle se trouvait à 2 coins de rue de là où j’étais sur la rue Main, ensuite il fallait que je tourne à droite, après à gauche et enfin à droite près d’un LCBO. Il m’a aussi dit que la bibliothèque serait à côté d’un établissement de soins pour personnes âgées.

Quand je suis arrivé à la bibliothèque, je me suis aperçu qu’elle était fermée. J’étais en colère! Bon sang! Pourquoi est-ce que l’on ferme les bibliothèques les dimanches? En plus, la personne qui m’a renseigné ne m’a même pas dit si la bibliothèque était fermée. Qui peut ne pas avoir besoin d’une bibliothèque le dimanche?

Tout en restant debout devant la porte d’entrée de la bibliothèque, je m’apitoyais sur mon sort. Pourquoi est-ce que je n’ai pas demandé au passant tout à l’heure si la bibliothèque était ouverte? Quelle sorte de gens posent des questions non spécifiques? C’est pour ça que j’ai eu un échec.

Après quelques instants de remords, j’ai voulu me calmer. Ma curiosité m’incitait à tourner mon regard à l’intérieur de la bibliothèque pour que mon mental puisse y trouver refuge. À chacun son médicament! Mais je n’arrivais pas à voir l’intérieur parce qu’il y avait un pare-soleil aux portes d’entrée, du côté intérieur bien sûr, qui faisait en sorte que je ne pouvais pas voir l’intérieur de la bâtisse. Ensuite, mon attention s’est tournée vers le porche de la bibliothèque. Là se trouvait une ancienne boîte postale en métal servant de chute à livre pour le retour de documents à l’extérieur des heures d’ouverture. L’artefact a été légué par Poste Canada à la bibliothèque, d’après ce que j’ai pu lire de l’écriteau qui se trouve sur la boîte postale. Je trouve que les bibliothèques sont écologiques et économes par nature. Au lieu d’utiliser ses ressources financières pour acheter une chute à livre, la bibliothèque préfère se servir de cette ancienne boîte postale de Poste Canada comme chute à livre.

Ensuite, après m’être calmé, j’ai quitté le porche de la bibliothèque. J’ai décidé de rebrousser chemin pour retourner sur la rue principale et reprendre le trajet pour me rendre à Pembroke, mais je savais d’avance que les bibliothèques de Pembroke seraient fermées parce qu’on était un dimanche. Ce qui m’irritait un peu c’est que demain serait un congé civique. Ce dernier est un jour férié que la majorité des municipalités ou provinces au pays décide de commémorer ou de célébrer un événement ou une personne: la fête du Patrimoine en Alberta, la fête du Nouveau-Brunswick et le Jour du Colonel By à Ottawa sont des exemples. Ce qui est sûr, c’est que demain il n’y aura aucune bibliothèque d’ouverte. Si j’avais fait mon voyage à vélo dans la province du Québec, j’aurais pu trouver facilement une bibliothèque ouverte puisque cette province n’a pas ce jour férié.

J’ai décidé de rebrousser chemin pour sortir de Cobden afin de me diriger à Pembroke. Sur mon chemin de retour sur la rue Main, à moins de 10 mètres de l’endroit où j’avais demandé à un passant où était la bibliothèque, quelque chose sortait de l’ordinaire dans la rue. C’est comme s’il y avait des troncs d’arbre de poteaux électriques qu’on avait regroupés et coupés pour mesurer tout au plus 7 pieds de haut. C’est en m’approchant de ces troncs d’arbres que j’ai vu qu’il s’agissait en fait de ce que l’on appelle en anglais «Little Free Library». Ça m’a fait plaisir de voir cela.

Jusqu’à présent, je suis content de trois choses. Premièrement, d’avoir pu trouver la bibliothèque bien qu’elle fût fermée. Deuxièmement, le fait d’avoir réalisé ou accepter ma situation concernant mon échec à un cours dans mon programme et les conséquences qui viennent avec. Troisièmement le fait d’avoir vu une Petite Bibliothèque Communautaire dans la région.

J’avais pris une pause pour écrire dans mon journal et pour prendre une collation, mais je dois maintenant reprendre la route pour me diriger à Pembroke.
