[#chapter-eight]
= Bibliothèque publique de Pembroke

[.text-right]
*Lundi 1er août 2016* : _7:10 – 15 degrés Celsius_

Je suis à l’hôpital régional de Pembroke et il est présentement 7 heures 10 du matin. Nulle part où aller. Je savais que la journée allait être plate alors mon cerveau essayait de répertorier, d’après mon expérience, où l’endroit le plus susceptible d’avoir une bibliothèque à Pembroke pourrait être. Je me suis dit qu’il y avait trois choix: soit dans un hôpital, dans une église ou dans un foyer pour personnes itinérantes. J’essayais de trouver une bibliothèque pour méditer, car à chacun son médicament.

Je savais que d’habitude les hôpitaux ont généralement une bibliothèque ou un centre de documentation qui est plus ou moins accessible au public. Par exemple, le centre hospitalier pour enfants de l’est de l’Ontario (CHEO) a la bibliothèque de ressources familiales Kaitlin Atkinson, les visiteurs peuvent se ressourcer en y empruntant ou en consultant des livres. L’Hôpital Général d’Ottawa a aussi une bibliothèque, mais elle est réservée au personnel employé de l’hôpital. C’est la raison pour laquelle je dis que la bibliothèque d’un centre hospitalier est plus ou moins accessible au public. Je dois me renseigner d’avance pour savoir si elle l’est.

Puisqu’aujourd’hui est un jour férié, c’est sûr que la bibliothèque de l’hôpital sera fermée, mais au moins je saurai qu’il y a au moins deux bibliothèques dans cette ville: la bibliothèque publique de Pembroke et celle de cet hôpital. C’est la raison pour laquelle je suis ici à cet hôpital afin de savoir s’il y a une bibliothèque ou non et si c’est ouvert aux visiteurs. Comme ça, je pourrai retourner demain à l’hôpital pour participer à la bibliothèque.

Malheureusement, le préposé au triage, puisque je suis rentré par l’entrée de l’urgence de l’hôpital, m’a dit que cet hôpital n’a pas le budget pour s’offrir une bibliothèque. Le truc le plus proche d’un service de bibliothèque est l’internet. La préposée au triage a enchainé son discours en me disant que cet hôpital met à la disposition des patients et des employés trois ou quatre ordinateurs installés dans la cafétéria de l’hôpital. Elle m’a aussi dit que ces ordinateurs ont tous accès à l’internet, mais qu’il n’y a ni de livres ni de bibliothécaire. Faute de bibliothèque, je me suis dirigé à la cafétéria et je dois utiliser la bibliothèque virtuelle qu’est la toile.

[.text-center]
…

Ça m’a fait du bien de raconter mon problème quand j’étais à Cobden. Présentement, c’est le temps des Jeux olympiques. Je ne veux pas me comparer aux athlètes, mais je dois dire que c’est difficile de faire face à l’échec. C’est comme si tout mon corps et mon âme me disaient que ce n’est pas possible que ça soit passé ainsi au sujet de mon cours d’été. Le fait de ne pas pouvoir commencer ma maîtrise le mois prochain est un coup dur pour moi. Mais, il faut que je commence à m’adapter à cette nouvelle réalité. Je vais écrire un courriel à mon employeur pour lui dire que je ne pourrai pas déménager à Montréal et que, s’il n’a pas déjà trouvé quelqu’un pour me remplacer, je souhaite rester à mon poste. Aussi, je dois contacter par téléphone le propriétaire du logement que j’ai trouvé à Montréal pour lui expliquer ma situation et lui dire que je vais rester à Ottawa.

Dans un voyage à vélo, j’ai compris qu’il faut être simple, ne pas s’encombrer avec des bagages inutiles, ne garder que l’essentiel. C’est une question de survie. Alors, je me suis aperçu que je me complique la vie pour rien. Au lieu d’aller à Montréal, je pourrais faire une demande à mon université parce qu’elle offre le même programme, mais contrairement à Montréal je pourrais commencer ma maîtrise en janvier… Ce qui est nettement mieux que de rester à poireauter jusqu’en septembre de la prochaine année. Je crois que j’ai voulu aller à Montréal pour changer d’air et pour participer à beaucoup de bibliothèques, que ce soit au sein de la ville ou du Grand Montréal. Je n’avais pas du tout pensé à m'inscrire dans ce programme à mon université. Ce n’est pas une question qu’une université est meilleure que l’autre. Non, pas du tout! C’est plutôt que j’ai voulu changer d’air. J’aurais pu m’inscrire à l’Université McGill à Montréal, l’Université de Western Ontario à London, l'Université de l'Alberta à Edmonton,  l’Université de Toronto, L'Université de la Colombie-Britannique à Vancouver, l'Université Dalhousie à Halifax en Nouvelle-Ecosse, mais j’ai choisi d’aller à Montréal à l’Université de Montréal. C’est comme si j’avais une certaine nostalgie de Montréal. Je ne sais pas pourquoi j’ai ce sentiment. Ce n’est pas comme si j’avais vécu longtemps à Montréal. Je n’y ai vécu que deux jours, c’était à l’époque où je suis venu au Canada pour la première fois.

J’ai oublié de mentionner un fait important: où est-ce que j’ai dormi hier soir? Je suis arrivé à Pembroke vers 4 heures de l’après-midi hier. Je me dirigeais à l’ouest de la ville pour aller dans un terrain de camping, mais je me suis arrêté pour remplir ma gourde d’eau dans un Tims Horton. Ce dernier se trouve en arrière de la bibliothèque publique de Pembroke et en est séparé par un cours d’eau. Un cycliste m’a salué pendant que j’étais au Tim et on a discuté pendant environ 20 minutes. J’ai oublié son prénom, malheureusement, mais son nom de famille est Walsh. Il m’a dit qu’il est né en Écosse et qu’il vie à Toronto depuis 15 ans. Petite parenthèse, le cycliste a le même nom de famille qu’une bibliothécaire que je connais, mais elle, par contre, elle est née ici. Il m’a aussi raconté qu’il fait un voyage à vélo pour rallier Kenora à Cornwall. Kenora est une ville à l’extrémité ouest de la province d’Ontario et Cornwall se trouve à l’extrémité est. Je lui ai dit que j’aime bien mon voyage à vélo, mais qu’aujourd’hui il me semble que ma journée est ennuyeuse. Il m’a dit que c’est normal dans un voyage à vélo qu’il y ait des journées plus sereines ou plus tranquilles que d’autres. Aussi, il m’a conseillé de mettre du piment dans mon voyage à vélo quand je ne suis pas à la bibliothèque. Par exemple, allez voir les cultivateurs, les saluer pour savoir quels produits ils vendent et m’intéresser à ce qu’ils font. Il m’a aussi dit qu’au lieu de dépenser de l’argent chaque nuit pour dormir au terrain de camping, il vaut mieux dormir à la belle étoile dans une forêt ou dans un terrain vacant, en bivouac quoi, sinon mon voyage à vélo va vraiment me coûter cher selon lui. Comme ça, j’ai une expérience plus proche de la Nature. Je vais me sentir petit face à la Nature et je serai reconnaissant pour chaque moment. Je pourrai même augmenter mon estime de soi. Ce que ce cycliste disait me motivait beaucoup. J’ai voulu suivre ses conseils.

J’ai donc décidé de me trouver un endroit à l’extérieur d’un terrain de camping pour dormir. Ça a été un défi et une cause de stress pour moi. J’ai parcouru le secteur industriel de Pembroke plusieurs fois pour trouver un endroit pour camper. J’ai cherché un endroit pendant au moins deux heures. Souvent, je passais par le même endroit trois ou quatre fois pour vérifier si c’était sécuritaire. Je ne voulais pas qu’un patrouilleur de nuit vienne et me dise de déguerpir. J’ai finalement décidé de monter ma tente en arrière d’une église protestante qui se trouve dans le secteur industriel. Il n’était pas indiqué qu’il y aurait un culte tard dans l’après-midi, donc il n’y aurait pas d’activité qui se déroulerait à l’église. Aussi, j’avais prévu de partir de bonne heure le matin.

Comme c’était ma deuxième nuit, je n’avais pas besoin de la lumière du soleil pour pouvoir monter ma tente. Je pouvais le faire à l’aide de la lueur de ma lanterne de camping. En arrière de l’église, c’était très bien: l’endroit le plus paisible que j’ai trouvé. Je n’ai pas eu une bonne nuit de sommeil cependant.

À peine si j’ai fermé l’œil pour trois heures au total. J’ai bien dit trois heures au total pas d’affilées. J’avais de la difficulté à dormir parce que je ne me sentais pas en sécurité. Je me sentais comme si j’étais dans l’illégalité. Et pour dire vrai, j’étais dans l’illégalité. J’ai monté ma tente sur une propriété privée. Que cette propriété soit fréquentée pendant la nuit ou pas, j’étais tout de même dans l’illégalité. Pour pallier mon insécurité et pour me permettre de me calmer, j’ai fait beaucoup de mes exercices de relaxation.

J’ai fait des exercices que je considère simples: par exemple compter jusqu’à 10 en nommant des bibliothèques. Nommer 10 bibliothécaires que je considère comme des modèles. C’est important pour moi d’avoir un ou des modèles de gens que je voudrais être. Les qualités que je voudrais posséder. Le professionnalisme dont ils font preuve. Leur sourire. Leur façon de gérer une situation délicate qui s’est passée à la bibliothèque, etc.

J’ai nommé les 10 ateliers que j’ai aimés le plus. Je parle d’ateliers qu’a offerts la BPO et auxquels j’ai participé. Dans mon décompte, j’ai oublié de mentionner le cours de langue ukrainienne qui était offert un soir de semaine à la succursale Sunnyside. J’ai particulièrement aimé ce cours parce qu’il y avait deux bibliothécaires qui le suivaient aussi. Une qui travaille à la bibliothèque MacOdrum de l’université Carleton et une autre qui travaillait dans un cabinet d’avocats. Elles étaient jolies, captivantes et j’aimais dialoguer avec elles, mais elles étaient mariées. Ça a coupé court mes scénarios romantiques qui me trottaient dans la tête.

Comme je me sentais toujours stressé, j’ai fait d’autres exercices de relaxation juste pour augmenter mon niveau de concentration afin de ne pas tomber dans l’angoisse. Je considère que nommer 10 bibliothèques c’est facile, alors j’ai compté jusqu’à 30 et finalement jusqu’à 50. Ensuite, j’ai nommé des bibliothécaires qui portaient des baskets et ensuite les bibliothécaires qui ont exactement la même taille que moi. Les bibliothécaires sont souvent assis au poste d’accueil, ce qui fait que je ne vois pas leurs pieds et je ne connais pas non plus leur hauteur à moins qu’ils se lèvent pour me montrer un document ou quelque chose à la bibliothèque.

J’ai aussi nommé les bibliothécaires qui portaient une cravate. L’habillement d’un(e) bibliothécaire travaillant dans une bibliothèque publique est plus décontracté que celui ou celle qui travaille dans une firme d’avocat. Alors c’est rare qu’un(e) bibliothécaire porte une cravate. Cet exercice visait à augmenter ma concentration et à me débarrasser de mon anxiété en puisant dans mes souvenirs. À chacun son médicament! Je me suis arrêté à quatre bibliothécaires après 20 minutes de réflexion.

[.text-center]
…
Je me suis réveillé vers 5 heures du matin. Une chose qui m’étonne dans cette randonnée, c’est que je me réveille quand le soleil se lève tandis qu’à la maison j’aurais pu dormir jusqu’à 11 heures du matin. J’aime le fait de me réveiller tôt. Ce matin, je me suis même mis à m’imaginer avoir une maison dans laquelle il y a un grand puits de lumière dans ma chambre. Comme ça, j’aurais une sensation proche de celle que j’ai aujourd’hui. Par exemple, je rêve d’avoir tout un pan de mur de ma chambre composé de vitre dans ma maison idéale comme un des murs vitrés de la succursale Beaverbrook de la BPO.

Pour revenir à la planification de ma journée: aujourd’hui, je vais aller visiter les fermes au lieu de rester ici dans la cafétéria de l’hôpital. Il est encore tôt, donc je vais aller demander du lait de vache cru dans une ferme à l’extérieur de la ville. Je n’ai jamais goûté de lait cru depuis que je suis au Canada. Ensuite, vers midi, je vais prendre le chemin du retour pour aller à Ottawa. Puisqu’on est lundi, j’arriverai à la maison au plus tard ce mercredi. Je sens que j’ai assez médité et mes jambes sont fatiguées. De plus, j’ai beaucoup de choses à régler à l’école. Il faut que j’aille rencontrer mon adjoint scolaire, m’inscrire dans un autre cours pour la session prochaine et consulter la copie de mon examen final.
