[#chapter-nine]
= Bibliothèque publique de Deep River

[.text-right]
*Mardi 2 août 2016* : _19:10- – 24 degrés Celsius_

Après deux jours sans avoir eu accès à une bibliothèque publique, je suis heureux comme un poisson dans l’eau d’être à la bibliothèque publique de Deep River. Je me sens dans mon élément.

J’avais dit, lorsque j’étais à Pembroke, que j’allais retourner chez moi, mais je ne me sentais pas vraiment prêt à retourner chez moi. C’est à la bibliothèque publique de Deep River que j’ai constaté que je n’étais pas prêt et que j’ai bien fait de continuer mon voyage. Tout d’abord, je vais parler de ma journée d’hier à Pembroke.

En quittant l’Hôpital Régional de Pembroke, je ne suis pas allé visiter des fermes comme prévu. Je ne voulais pas sortir de la ville. J’ai fait deux tours de la partie est de la ville. Je prenais la route 41 qui se transforme en rue Mackay, puis j’ai tourné à gauche pour prendre la route 148 afin de rejoindre la route 41 au nord de la ville. Je cherchais quelque chose d’intéressant à faire ou à voir dans le secteur, mais je n’ai rien trouvé. Ensuite, je suis allé manger. Après, je me suis rendu à la bibliothèque de Pembroke juste pour me désennuyer. À chacun son médicament! Je savais déjà qu’elle était fermée en ce jour férié, mais je voulais pouvoir apprécier l’architecture.

La bibliothèque a de grandes fenêtres. J’ai cru voir du Mondrian dans le style des fenêtres. Piet Mondrian est un peintre connu pour ses tableaux faisant partie du mouvement néoplasticisme. Un tableau du mouvement néoplasticisme est comme une mosaïque d’éléments de forme carrée ou rectangle qui ont une bordure noire. Les carrés et les rectangles peuvent être de différentes tailles ou de couleurs. Le jaune, le rouge et le bleu sont les couleurs privilégiées pour remplir les carrés et les rectangles, mais ils peuvent aussi être peinturés de blanc et de noir.

Comme je l’ai mentionné plus haut, je trouve que les fenêtres de la bibliothèque publique de Pembroke ont un style de composition de grilles un peu comme les peintures de Piet Mondrian. Je veux dire par là qu’une fenêtre est construite de multiples vitres qui sont séparées par une planche de bois au lieu des bordures noires de Mondrian, de manière à ce qu’on voie des vitres de formes rectangulaires ou carrées. Les couleurs primaires ne sont pas peinturées sur la vitre, mais certaines vitres sont peinturées de divers tons de bleu.

Je me tenais à côté de mon vélo en avant de la bâtisse tout en bas de l’escalier pour regarder les fenêtres. Le point décisif de ma journée à Pembroke s’est déroulé à ce moment, devant la bibliothèque. J’ai rencontré une madame du nom de Francine. Elle avait garé sa voiture sur la rue au lieu de rentrer dans l’aire de stationnement qui se situe du côté droit de la bibliothèque. Elle avait emprunté des livres et voulait les déposer dans la chute à documents, mais elle en avait emprunté trop et elle voulait les emporter tous d’un seul coup de sa voiture à la chute à livres. J’ai vu qu’elle avait besoin d’aide. Je l’ai saluée avec un sympathique «Comment ça va?» et je lui ai aussi demandé «Avez-vous besoin d’aide?» Elle a répondu «_Komsémné_» et «Awaye donc». J’étais perplexe. J’avais compris ce que veut dire «Awaye donc», mais je n’ai pas compris ce qu’elle m’a dit au début. J’ai même pensé qu’elle parlait une autre langue. Par réflexe, je lui ai redemandé si elle avait besoin d’aide. Elle m’a répondu encore: «Awaye donc».

Je l’ai aidée à transporter ses livres pour les déposer dans la chute à documents tout en continuant à converser avec elle. J’ai voulu savoir ce que ça mange en hiver «_Komsémné_». Elle m’a expliqué que son père avait l’habitude de répondre cela. Son père n’était pas très bavard, mais il était toujours franc. Elle m’a expliqué que l’expression «_Komsémné_» veut dire «comme c'est mené». Alors, j’ai dit «Ah. J’ai compris».

Tout de suite, je me suis ravisé parce que je me suis aperçu que je ne comprenais pas l’expression «comme c’est mené». Alors, je lui ai demandé d’où vient cette expression et ce que ça veut dire. Elle m’a expliqué que ça venait sûrement de l’ancien temps. Elle a spécifié que ça venait de l’époque de la colonie française. Elle enchaina :
    * Mon père était cultivateur et il utilisait une charrue pour labourer sa terre. «_Komsémné_» est une expression qu’utilisaient les cultivateurs. Si vous menez bien votre charrue alors vous aurez de belles lignes droites au sol, en l’occurrence un labour régulier. En d’autres mots, ça veut dire que si vous gérez bien vos affaires, tout se passera pour le mieux. T’as le résultat de ton niveau d’effort et de discipline appliquée à la tâche que tu fais. C’est une façon d’être dans le moment présent, de se responsabiliser, de s’affirmer et de prendre conscience de sa situation. C’est une façon de prendre un moment de réflexion et de constater sa situation, que l’on aime ou pas. L’important est d’en prendre conscience. Il faut qu’à chaque fois que tu prononces «_Komsémné_», tu puisses faire face à ta réalité.
Elle m’a dit qu’elle avait de la difficulté à transporter ses livres et certains des livres étaient sur le bord de s’échapper de ses bras pour tomber par terre. Alors, elle me dit qu’elle n’allait tout de même pas me répondre «oui ça va bien».

Je lui ai dit que c’était une bonne expression, mais que j’ai toute même peur d’offenser les gens en l’utilisant, parce que je la trouve un peu bête, voire sarcastique. Elle m’a répondu que c’était l’expression de son père et qu’elle l’utilise souvent pour commémorer la façon dont son père, qu’elle aimait réellement, parlait.

Elle m’a aussi dit qu’elle ne trouve pas que l’expression sarcastique, elle la trouve plutôt réaliste. En fait ce qu’elle trouvait sarcastique, c’est quand elle va au dépanneur et que le caissier lui dit «comment ça va?» et qu’elle, elle répond «ça va bien». Elle croyait que les gens qui posent la question se fichent bien de savoir comment l’autre va et ceux qui répondent, s’e fichent aussi d’exprimer leur situation. Elle m’a éduqué! C’est une dame plein de gaieté et de franchise. On a jasé une bonne quinzaine de minutes, à l’ombre près de la chute à documents. Elle m’a raconté beaucoup de choses: qu’elle est métisse et franco-ontarienne, qu’elle est née dans la région de Pembroke, que son père venait d’un petit village à côté de Sherbrooke au Québec. Elle m’a même parlé de la bibliothèque publique de Pembroke. Elle m’a dit qu’on a fêté le 100e anniversaire de l’immeuble en 2014. Elle m’a parlé de feue Alma Beaty, la première bibliothécaire à la bibliothèque de Pembroke. Sans aucun doute, il faut que je revienne un jour à Pembroke pour visiter cette bibliothèque. Je trouve que Francine connait très bien sa bibliothèque. Elle m’a aussi dit que c’est une bibliothèque Canergie. Andrew Canergie est un philanthrope né au 19e siècle qui a financé la construction de bibliothèques publiques à travers le monde par le biais de sa fondation. On qualifie une bibliothèque qui a été financée par la fondation Canergie de bibliothèque Canergie. Par exemple, la succursale Rosemount de la BPO est une bibliothèque Canergie. Pour revenir à ma conversation avec Francine, je lui ai parlé de ma venue au Canada en 1991, du voyage que je fais présentement, de mes études qui ne vont pas très bien, etc. Ensuite, on s’est quittés malheureusement, parce qu’il faisait trop chaud.

J’ai exploré les environs de la bibliothèque. J’ai eu la chance de rencontrer le diacre Adrien Chaput qui a été bien aimable d’ouvrir les portes de la cathédrale Saint Columbkille pour que j’aille la visiter. J’en ai même profité pour faire une prière. En sortant de l’église, j’ai demandé au diacre de se servir de mon cellulaire pour me prendre en photo. C’est à ce moment que j’ai réalisé que je n’avais pas encore pris de photo de moi durant le voyage. Je n’ai que pris des photos des bibliothèques que j’ai visitées.

Ensuite, on s’est dit au revoir. De l’endroit où j’étais, je me suis dirigé vers le nord-ouest de Pembroke par la rue Pembroke Ouest. Après avoir pédalé à peine 15 minutes, j’ai constaté, à l’aide d’un panneau de signalisation routière, que la route où je circulais menait à Petawawa. Alors, je me suis dirigé vers cette ville juste pour le plaisir de pédaler. Après Petawawa, je me suis dirigé vers Deep River parce que, tant qu’à y être, mieux vaut continuer mon voyage vers le nord d’ouest. De plus, je n’avais pas noté sur ma carte s’il y avait une bibliothèque à Petawawa, mais j’en avais noté une à Deep River. C’est la raison pour laquelle je ne me suis pas attardé à Petawawa.

À mi-chemin entre Petawawa et Deep River, sur l’autoroute 17, j’ai rencontré une autre femme. Je n’ai pas retenu son nom. C’est un de mes défauts: j’ai de la difficulté à retenir les noms des gens. Elle sortait du travail et empruntait la route pour s’en aller chez elle en direction de Deep River. Elle s’était arrêtée en bordure de l’autoroute 17 pour cueillir des bleuets. Elle m’a invité à en faire de même. J’ai accepté. D’une certaine manière, je n’avais pas le choix parce que je n’avais plus de collations et j’avais vraiment faim. J’avais encore de l’eau, mais plus rien à manger. Elle m’a dit qu’il y avait cinq différentes sortes de bleuets qui étaient présents là où l'on était et elle m’a appris à les identifier. J’en mangeais pendant que j’en cueillais. J’ai réussi à remplir deux petits sacs Ziploc pour subvenir à mes fringales durant le trajet jusqu’à Deep River.

Je n’avais jamais mangé de bleuets, en plus de 20 ans au Canada. En fait, j’ai mangé des muffins aux bleuets et des tartes aux bleuets, mais je n’en ai jamais mangé cru et frais comme pour les fraises et les framboises. Le goût des bleuets est succulent. Rien à voir avec le goût des muffins aux bleuets, remplis de sucre synthétique, que j’achète au Tim Hortons. Je trouve que c’est mieux de les manger frais et j’ai aussi trouvé qu’ils sont de formidable coupe-faim. Ça m’a rassasié!

Je suis arrivé à Deep River en fin d’après-midi. Je suis allé me balader dans la ville pour savoir où était située la bibliothèque. Ensuite, j’ai soupé dans un resto. Par la suite, j’ai circulé dans la ville pour chercher une place où dormir. J’en ai trouvé une près d’un boisé qui se trouve en arrière d’un magasin d’artisanat sur l’autoroute 17. Alors, ceci conclut le résumé de ma journée d’hier.

[.text-center]
…

Aujourd’hui, je me suis levé tôt à cause du lever du soleil. Je crois vraiment que mon horloge biologique est réglée en fonction de notre Étoile. Ensuite, je suis allé prendre un verre d’eau chaude au Tim-Hortons. Le matin, j’aime boire un verre d’eau chaude, j’en ai pris l’habitude depuis plus d’une dizaine d’années. Un peu plus tard, j’ai pris le petit-déjeuner dans un café qui s’appelle The Bean House à moins d’une minute à vélo de la bibliothèque publique de Deep River.

Je suis présentement à la bibliothèque publique de
Deep River. Dès mon arrivée, à 10 heures du matin,
l’heure de l’ouverture, je me suis renseigner en anglais
auprès de Tom, le bibliothécaire. J’ai appris beaucoup
de choses, entre autres, que c’était une bibliothèque
privée auparavant qui portait le nom de Wilfrid Bennet
Lewis, un scientifique canadien ayant comme champ
d’expertise la technologie nucléaire.

J’ai utilisé un ordinateur de la bibliothèque pour voir si mon employeur avait répondu à mon courriel. Pas encore. En après-midi, je suis sorti pour aller visiter les environs. J’ai visité le musée canadien de l’Horlogerie qui se trouve à moins de 5 minutes de la bibliothèque à vélo. J’ai aussi profité de la plage à Deep Grove parce que ça faisait deux jours que je ne m’étais pas baigné. Je ne puais pas, enfin, je l’espère! Je ris de moi-même. Mais, je dois dire que ça m’a fait du bien d’aller me baigner surtout avec cette chaleur qui sévit depuis samedi.

[.text-center]
…

À mon retour en après-midi, je dois dire que j’étais content de voir que mon employeur a répondu à mon courriel. Il m’a dit qu’il y aura toujours une place pour moi dans la compagnie et qu’il n’avait pas engagé un nouvel employé. Mais j’avais encore peur de l’avoir déçu. Je crois que même s’il trouve que je suis un bon employé, il espérait que j’aspire à un avenir meilleur en commençant ma maîtrise. Pour revenir à la bibliothèque, il y a un objet très intéressant, une horloge. C’est une «American Black Mantle», donnée à la bibliothèque par le musée canadien de l’Horlogerie. Je crois que le mot «mantle» ou «mantel» peut se traduire en français par «manteau» comme pour un «manteau de cheminée» qui est la finition décorative tout autour du foyer. L’«American Black Mantle» est un type d’horloge dit de cheminée ou de foyer parce qu’on place généralement l’horloge sur le manteau de cheminée.

Je trouve que d’avoir placé cette horloge sur le manteau de cheminée de la bibliothèque publique de Deep River apporte une touche traditionnelle et rustique au décor. Le carillon de l’horloge sonne chaque heure et un coup à la demi-heure. Ça m’a étonné, c’est la première fois que j’entends le carillon d’une horloge qui sonne aussi fort dans une bibliothèque. D’habitude, le son est bas pour ne pas perturber les lecteurs. Après mûre réflexion, je trouve que le son du carillon de l’horloge est doux pour les oreilles sauf la première fois que je l’ai entendu sonner.

J’ai longuement cogité sur cette horloge et sur la notion du temps. Chaque mouvement de l’aiguille dure une seconde et chaque seconde est différente de la précédente. Je veux dire par là que les événements qui se produisent à une seconde donnée seront différents à la prochaine seconde si l’on tient compte de l’espace-temps. Le contenu du journal d’hier n’est pas le même que celui d’aujourd’hui, même si les nouvelles étaient mises sous presse à la même heure chaque jour. Ce qui m’a fait penser que je n’avais pas lâché prise. Mon temps s’est arrêté depuis jeudi dernier, le jour où j’ai reçu mes notes finales pour les cours que j’ai suivis cet été. Je m’en voulais encore d’avoir eu un échec. Logiquement, j’avais accepté ma situation, mais dans mon cœur je n’étais pas en paix.

Cette horloge me faisait penser au temps et à la distance parcourue. Si j’ai une blessure, il est important de prendre le temps pour la laisser guérir. Il faut que j’utilise les ressources qui me sont offertes pour pouvoir guérir. Comme je me dis souvent «à chacun son médicament»! De la Bibliothèque publique de Pembroke, j’avais besoin d’aller voir une autre bibliothèque avant de retourner à Ottawa: chez moi à Orléans, plus précisément. Il est important que je laisse le temps faire son temps. C’est à cause de l’horloge de la bibliothèque que j’ai décrite plus haut que j’ai réalisé que je n’étais pas prêt à retourner à Ottawa. Il me fallait encore du temps.

Tout en continuant ma réflexion sur l’horloge, le temps et de l’expression «_Komsémné_», j’ai réalisé que je n’avais pas pris les moyens de réussir. Si je n’avais pas suivi deux cours d’été et si j’avais consacré plus d’heures à l’étude et moins d’heures au travail, je crois que j’aurais augmenté mes chances d’avoir une meilleure note. Tous les signes étaient là, mais je ne les ai pas vus. J’étais préoccupé par autre chose, sûrement le travail ou le fait que je me préparais à déménager dans une autre ville. J’avais les pensées ailleurs au lieu d’étudier pour le cours de comptabilité. Je dois avouer que la vie fonctionne en bonne partie «_Komsémné_».

Demain, je m’en vais directement à la bibliothèque publique John Dixon à Mattawa, car je veux poursuivre mon voyage à vélo. D’après ma carte géographique, c’est une longue route d’ici à Mattawa et il me semble qu’il y a beaucoup d’élévations, ce qui veut dire qu’il y a des montagnes. De plus, je sais que le soleil va augmenter ma fatigue alors je compte partir tôt pour arriver le plus rapidement possible pour participer à la bibliothèque John Dixon. Ensuite, je retourne chez moi à Orléans pour me reposer du voyage à vélo avant de recommencer le boulot.

[.text-center]
…

Il y a un bus voyageur qui fait la liaison Mattawa-Ottawa chaque jour. En fait, l’autobus passe en pleine nuit vers les deux heures du matin. J’ai appelé Greyhound, une compagnie d’autocar, plus tôt dans l’après-midi pour savoir si un service faisait le trajet Mattawa-Ottawa et connaitre quelles seraient les procédures pour transporter ma bicyclette.

Ottawa-Mattawa, ça me convient ! De plus, ça rime. Je ne m’en veux pas trop de ne pas pouvoir me rendre à North Bay. J’ai une contrainte de temps et des affaires à régler à Ottawa, ce qui fait que je ne peux pas m’attarder plus longtemps au voyage. Je dois dire que, pour un premier voyage à vélo, je suis satisfait et j’aime la persévérance dont j’ai fait preuve. Au début du voyage, je voulais rentrer chez moi. Pourtant, le voyage jusqu’à présent vaut entièrement la peine.

En résumé, à Mattawa, je prendrai l’autobus voyageur pour me rendre à Ottawa. Je n’aurai pas besoin de retourner à bicyclette, ça aurait pris trop de temps et j’ai besoin de quelques jours de repos avant de recommencer ma vie effrénée.
