[#chapter-ten]
= Bibliothèque John Dixon : Bibliothèque publique de Mattawa

[.text-right]
*Mercredi 3 août 2016* – _23 degrés Celsius_

[.text-center]
…

La vie est mystérieuse

[.text-center]
…

Il y a tant de choses à découvrir.

[.text-center]
…

Parfois, j’arrive dans un lieu ou dans une ville et je me mets à rêver de m’y installer. C’est comme ça que je me suis senti quand je suis arrivé à Mattawa. Je me dis que ça serait bien de vivre ici. Il y a quelque chose d’accueillant dans cette ville. Je ne peux pas le définir. L’atmosphère me semble fascinante, je n’ai pas encore fait le tour de la ville, mais je l’aime bien. Il y a quelque chose de serein et de spirituel ou c’est peut-être moi qui vois les choses autrement.

Je suis profondément joyeux. «Joyeux», pas dans le sens de «j’ai réussi», ou «j’avais raison», mais «joyeux» dans le sens de, content d’«être», de «j’apprécie». La vie est mystérieuse. J’ai l’impression que tout ce qui se passe dans ma vie devait se passer ainsi, que j’aie travaillé assez ou pas assez, je me sens comme si tout devait se passer ainsi! Que je suis là où je devrais être. C’est difficile pour moi de mettre des mots sur ce que je ressens.

[.text-center]
…

La paix intérieure, c’est quelque chose de précieux.

[.text-center]
…

Oh si je pouvais rester dans cet état toute ma vie!

[.text-center]
…

Parfois, j'entends dire, de la bouche de quelqu’un qui a le cancer, qu’il ne souhaite sa maladie à personne, mais que la situation dans laquelle il se trouve est la meilleure chose qui aurait pu lui arriver. Ce n’est pas le cancer, mais la paix intérieure qui fait que la personne voit la vie d’une manière totalement différente, voire se crée des solutions là où il n’y en a pas.
Dans la même veine, quand j’arrive devant une montagne ou une difficulté et que je pense que c’est la fin de la route, je commence à maudire ma situation. Si j’ai bien travaillé, je me dis que c’est injuste que ça se passe ainsi. Si je n’ai pas assez travaillé alors je dis que c’est juste, mais que je n’aime pas ce que je suis en train de vivre. Vivre une paix intérieure fait en sorte, que peu importe la situation dans laquelle je suis, je sens que c’est le meilleur endroit où je pourrais être parce que je ne vois que des possibilités qui s’offrent à moi. Comme si la paix intérieure faisait des routes là où il n’y en avait pas.

[.text-center]
…

De Deep River à ici, que la route était belle! C’était toute une aventure. De toute la randonnée, c’est la partie que j’ai aimée le plus, tellement le paysage était pittoresque. Ça a aussi été un challenge pour moi de parcourir tous ces kilomètres à vélo.

Un challenge parce qu’il y avait beaucoup de montagnes à gravir, de vents à affronter, de véhicules à surveiller, surtout les poids lourds. Souvent, je m’arrêtais et je regardais le camionneur dans les yeux pour m’assurer qu’on ait un contact visuel avant de me remettre à pédaler. On ne sait jamais: un accident est si vite arrivé. Je me suis aussi vêtu d’une veste de cycliste de couleur vive pour augmenter ma visibilité à vélo auprès des automobilistes.

[.text-center]
…

Je trouve que la vue était magnifique en haut des montagnes. Oui, des montagnes, j’en ai grimpé beaucoup à vélo. À chaque montagne que j’avais fini de gravir, arrivé à la cime (le point le plus élevé de la montagne), je m’arrêtais pour admirer le chemin parcouru et je prenais un moment pour apprécier la descente mentalement. Je trouve que j’ai une certaine euphorie quand je dévale une montagne à vélo alors je me prépare mentalement à savourer la descente.

[.text-center]
…

Oui, le mari de Jacynda avait raison au sujet de gravir les montagnes à vélo. Je ne crois pas avoir mentionné de Jacynda et son mari dans mes écrits. C’est un couple très dynamique qui aime particulièrement faire des voyages à vélo. de Jacynda étudie à l’université près de la ville d’Hamilton en Ontario. Elle fait beaucoup de compétitions sportives et je trouve qu’elle a un grand cœur: elle m’a offert une lampe que je peux fixer à mon vélo. Son mari, lui, est perspicace, très sage et il aime aider les gens. Ils étaient mes voisins du lot que j’ai loué pour dormir dans le terrain de camping de Serenity Hills. C’était la période après avoir visité la bibliothèque publique d’Arnprior.

Je me rappelle d’une conversation que j’ai eue avec le mari d’de Jacynda. J’ai oublié son nom malheureusement. On parlait de ce que l’on aime le moins quand on fait du vélo. Moi je lui disais que c’était les montagnes, il a acquiescé, mais il m’a dit que de rouler contre le vent est pire que grimper des montagnes à vélo. Moi, je trouvais que les montagnes étaient pires parce que mes jambes s’épuisent plus rapidement que lorsque je n’ai qu’à me soucier du vent.

C’est maintenant que je réalise qu’il a un meilleur argument que le mien. Le mari d’de Jacynda me disait que, quand il roule face contre vent à vélo, il ne sait pas quand le vent va cesser tandis que quand il gravit une montagne, il risque de rechigner et de se plaindre que ses muscles jambiers lui font mal, mais de ses yeux, il peut juger la distance qu’il lui reste à parcourir pour arriver à la cime. De là, il sait quand sa souffrance va être terminée. Autrement dit, sa souffrance à une fin. Par contre, il ne peut pas prévoir quand le vent s’arrêtera. Il n’a aucun point de repère. Il ne peut pas se fier aux nuages ni aux balancements des branches d’arbres pour prévoir quand le vent cessera. Après avoir grimpé toutes ces montagnes et pédalé parfois face au vent, je trouve qu’il a entièrement raison. Rouler face au vent est le pire!

[.text-center]
…

Petite parenthèse. Je m’en rappelle maintenant, de son prénom. Phillip! C’est ça le nom du mari d’de Jacynda. C’est Philip.

[.text-center]
…

Je suis ici à la bibliothèque publique John Dixon. Je me sens en paix mentalement, spirituellement et émotionnellement. Tellement en paix que j’ai oublié de calculer combien de temps ça m’a pris pour arriver ici. C’est une information qui n’est pas importante. J’ai encore beaucoup de temps avant que la bibliothèque ferme. Je vais donc me permettre d’écrire le plus que je peux parce que mon périple à vélo se termine ici. Je me sens en paix et ça me suffit. Je crois avoir parcouru assez de kilomètres pour clore mon premier voyage à vélo.

La bibliothèque publique de Mattawa est l’endroit idéal pour terminer mon excursion. La bibliothèque est située dans une institution scolaire. C’est comme si le lieu m’invitait à me plonger dans mon enfance. Mon enfance, en Haïti. Je me rappelle ma cour d’école, le fait de jouer au football (ou soccer, comme on dit au Canada) dans la cour avec mes camarades de classe, les rires, les joies, les peines, le fait de se mettre en rang pour faire la rentrée en classe à la fin de la récréation, etc. Tous ces souvenirs refont surface dans mon esprit, mais sans provoquer de panique et de regret.

Mon enfance, c’était l’époque de la guerre en Haïti. Je devais avoir 6 ans ou 7 au max. Je ne me souviens pas de la guerre, de qui était l’ennemi. C’est juste une façon pour moi d’exprimer que c’était le chaos. En fait, je crois que j’ai choisi le mauvais mot. Ce n’était pas ni une guerre ni le chaos, c’était une période d’instabilité politique. Mais je trouve aussi que le terme instabilité politique est un peu vague. C’était en 1991, je ne veux pas nommer les partis politiques ou les figures marquantes de cette période. De toute façon, avec le recul, je crois que même si l’on changeait les têtes d’affiche, on aurait eu le même résultat. Ce n’était pas une période pour vivre sécuritairement en Haïti. Le pire c’est que l’instabilité politique perdurait depuis bien avant les dates que j’ai mentionnées malgré les changements de gouvernement. De nos jours, la situation économique et politique est beaucoup mieux.
Je me rappelle un événement précis dans mon enfance, toujours dans la même période de l’instabilité politique. C’était un jour comme tous les jours d’école. J’étais en élémentaire 1. L’équivalent de la 1re année du primaire. C’était le jour du vocabulaire. En ce jour, le professeur, qu’on devait appeler «maître Roger», a demandé à chaque étudiant d’épeler trois mots, ce qui n’a rien d’un événement douloureux a priori. Mais la pratique de la pédagogie était différente. Si l'on épelait mal le premier mot, on avait trois coups de rigwaz. Un rigwaz est un fouet. Si j’essaie de concevoir la manière dont un rigwaz est fabriqué, j’évoque ce procédé: on prend deux lainières de peau de bœuf (elles sont de deux à trois pieds de longueur et d’une largeur d’environ d’un demi-pouce) et on les tresse. On les laisse sécher au soleil pendant quelques jours, ce qui fait que les lanières tressées durcissent. Le fouet a dorénavant l’apparence d’une tige effilée, mais a une certaine flexibilité quand on fouette. Appliqué sur la peau, le fouet brûle. J’ajouterais aussi qu’il y a quelques technicités dans la manière de fabriquer le rigwaz que je ne connais pas, ce qui fait que certains rigwaz étaient fabriqués pour que ça fasse plus mal que d’autres.

Alors, comme je disais, la pratique pédagogique adoptée par le professeur était que je reçoive deux coups de rigwaz si j’épelais mal le mot demandé. Ensuite, pour le deuxième mot, je recevais 4 coups de rigwaz et pour le troisième mot, 10 coups. Alors, voilà ce qu’étaient les règles. Généralement, après 3 coups je ne pouvais plus supporter la douleur.

Pour revenir à mon histoire, le maître Roger m’a appelé par mon prénom et m’a demandé d’épeler trois mots suivant le thème qu’on nous avait enseigné la veille. Les trois mots étaient les suivants: «pompier», «ambulance» et «bibliothèque». La veille, on nous avait enseigné les types de services qui sont offerts dans la ville. Comme devoir, on avait un ensemble exhaustif de vocabulaire relié au terme vu en classe. Les vocabulaires étaient tirés principalement du dictionnaire et secondés par un manuel scolaire que seul le professeur possédait. Le professeur devait donc écrire les mots au tableau. Les élèves écrivaient ces mots dans leur cahier de notes et devaient les apprendre par cœur pour le lendemain.

Pour poursuivre mon histoire, je me suis levé de ma chaise pour me tenir debout afin d’épeler le mot «pompier». Quand j’ai terminé d’épeler le mot, je hochais la tête pour avertir le professeur. À l’instant, j’étais sûr que j’avais bien épelé le mot «pompier», mais ce n’était pas le cas. Je ne savais pas quelle était mon erreur, mais le professeur m’a demandé de montrer mes deux plantes de main et il m’a infligé vigoureusement 2 coups de rigwaz. Une dans chaque main.

Au deuxième mot, j’ai mis des «e» à la place des «a» dans le mot «ambulance». Alors, le professeur m’a donné 4 coups. Ça fait vraiment mal, les coups de rigwaz. Zéro en deux, j’étais déçu de ma performance! J’aurais voulu que le maître Roger se passe des coups de rigwaz et qu’il me dise tout simplement que je n’avais pas assez étudié. Mais, à l’époque, c’était la façon dont mon professeur corrigeait ses élèves. À chacun son médicament, à chacun sa manière de procéder pour se sentir satisfait.

Je pleurais comme une madeleine quand il m’a demandé d’épeler le troisième mot, «bibliothèque», parce que les précédents coups de rigwaz me faisaient encore mal. Il me le demandait avec un ton de colère et il m’a appelé par le nom que certains de mes camarades utilisaient pour me désigner: «Bèg», un mot créole qui sert à désigner quelqu’un qui bégaye. Oui, je ne l’ai pas mentionné, mais dans mon enfance, je souffrais de bégaiement. Je considère que le maître Roger était quand même patient parce qu’il attendait mon signal d’hochement de tête avant de frapper, peu importe le temps que ça m’a pris  pour épeler le mot. Pour le troisième mot, j’ai eu une sorte de perturbation dans mon esprit, comme si quelque chose n’était pas normal. Je me suis concentré et je l’ai bien épelé. Le maître Roger m’a félicité. Le mot «bibliothèque» m’a épargné des coups de rigwaz.

Je me suis rassis sur ma chaise, mais j’ai pris quelques secondes avant de tenir mon crayon dans ma main parce que je n’avais pas beaucoup de dextérité fine. Les coups de rigwaz que j’avais reçus me faisaient encore mal. Il fallait que j’attende que la douleur s’en aille. Soudain, mes pleurs s’estompèrent, mais j’avais l’impression que quelque chose n’avait pas de sens. On me demande des choses qui n’existent pas dans mon environnement. «Pompier»! Je me répétais dans la tête plusieurs fois le mot «pompier». J’essayais de recenser les fois que j’ai vu un pompier à Port-au-Prince. J’ai vu un camion de pompier dans les Transformers, une bande dessinée que j’ai vue à la télé, mais à Port-au-Prince? Un «pompier»?
Je me rappelle quand le feu a pris chez tatie Clara une voisine qui habitait à trois maisons à gauche de chez nous. Je n’ai jamais vu de pompiers venir éteindre le feu. C’était tout le voisinage qui venait avec des seaux remplis d’eau pour pouvoir aider à éteindre le feu. Je vois les problèmes, mais je ne vois pas de solutions dans lesquelles je peux mettre le mot «pompier».

Le deuxième mot, «ambulance», est aussi étrange que le premier dans l’environnement que je vivais. Je sais qu’il y a des hôpitaux à Port-au-Prince, mais je n’ai jamais vu d’ambulance. Je sais aussi qu’il y a des gens qui m’ont raconté qu’ils ont été hospitalisés d’urgence, mais je ne sais pas comment ils ont fait pour partir du point A pour rejoindre le point B. Non, j’ai tort! Oui, j’ai des exemples concrets qui démontrent comment le point A fait pour rejoindre le point B, mais pas par ambulance. Cette dernière n’est pas dans l’équation. Soit on y va à pied, à l’hôpital, soit on prend une «camionèt», qui est l’équivalent d’un taxi en français. Si on est assez chanceux pour connaître quelqu’un dans le voisinage qui a une voiture, on peut lui demander de nous amener.

Je me rappelle aussi maître Antoine, ou comme les plus grands l’appelaient dans le quartier, maître Ti-Zo. Il était journaliste de profession, mais comme à l’époque il ne pouvait pas vivre que de cela, il était aussi professeur et peintre. Il habitait à un coin de rue d’où je demeurais. La mère de maître Antoine était jadis le professeur de ma mère. Mes parents entretenaient de bonnes relations avec maître Antoine: il faisait presque partie de la famille. Maître Antoine m’aidait en mathématiques parce que j’avais de la difficulté à l’école dans cette matière. J’allais chez lui deux à trois fois par semaine et je me sentais comme chez moi, voire mieux. Maître Antoine avait le don de bien enseigner et c’est vraiment la meilleure personne que j’ai vue jusqu’à présent, tellement il avait bon cœur et tellement il était drôle. J’aimais aller chez lui: il avait trois bibliothèques remplies de livres. Les bibliothèques d’environ 5 pieds étaient encastrées dans une partie d’un des murs du salon. Elles ressemblaient à celles de la succursale Rideau de la BPO qui sont encastrées aux murs du premier étage. Maître Antoine me laissait emprunter des livres pour que je sois plus cultivé et pour que je puisse m’améliorer à l’école. Il faisait le même geste avec d’autres gens du quartier aussi.

Pour revenir à mon histoire principale, un jour où maître Antoine rentrait chez lui, un malfaiteur l’attendait. Arrivé devant sa barrière, le malfaiteur lui a tiré dessus, au niveau de l’abdomen. Même aujourd’hui, je ne sais pas pourquoi on a tiré sur le maître Antoine. J’ai entendu dire que c’est parce qu’il s’est fourré le nez dans une affaire qui ne le regardait pas. En d’autres mots, il critiquait le pouvoir en place. Il y avait d’autres rumeurs dans le quartier, par exemple on disait que le maître Antoine avait un parti-pris ou qu’il était partisan d’un parti politique. Ça, je ne le crois pas. Il était journaliste de profession et, le connaissant, ce n’est pas quelque chose qu’il ferait, mais quoi qu’il en soit, à l’époque, j’ai compris qu’être partisan voulait tout simplement dire être condamnable. Quand le malfaiteur est reparti dans une voiture, certains voisins et mes parents par la suite, sont accourus pour lui venir en aide. Tout le monde a fait des pieds et des mains pour trouver un moyen pour amener maître Antoine à l’hôpital. Mais parmi tous les gens qui se sont dit qu’il fallait que maître Ti-Zo se rende à l’hôpital, nul n’a pensé à prononcer le mot «ambulance».  J’étais présent quand j’ai vu que des gens du quartier ont aidé à maître Antoine à l’arrière d’un pick-up. Maître Antoine est décédé de ses blessures, si je me fie à ce que j’ai entendu de la conversation de mes parents, quelques heures plus tard. Il était décédé avant même d’arriver à l’hôpital. Ça m’a traumatisé.

[.text-center]
…

Quant au mot «bibliothèque», je n’en parle pas, je n’en ai jamais vu dans mon enfance. Je parle d’une bibliothèque publique ou de quartier et même de celles privées. Par exemple, mon école n’avait pas de bibliothèque. Je ne sais pas pour les universités. Mais ce qui est important, c’est que le fait, que j’ai bien épelé le mot bibliothèque a fait en sorte que j’ai été épargné des coups de rigwaz. Ça m’a permis de prendre conscience de la réalité dans laquelle je vivais.

Je ne sais pas où l’école achetait leur manuel scolaire, mais ce livre ne faisait pas partie de la réalité de la ville où je vivais à cette époque-là. Peut-être, que le manuel scolaire faisait partie de la réalité Cap-Haïtienne ou Jacmélienne, mais pour Port-au-Prince, je ne crois pas! Il y a des mots qui n’existent que dans des dictionnaires et dans les manuels scolaires.

Si une bibliothèque existe, c’est que j’existe. C’est pour cela que j’aime les bibliothèques. L’épellation du mot «bibliothèque» a été le déclic.

[.text-center]
…

La plupart des gens trouvent les bibliothèques silencieuses, mais moi je les trouve bruyantes. Bruyantes d’idées, de suggestions, d’histoires et de faits. C’est comme si tous les auteurs m’invitaient à lire, à entendre, à regarder ou à participer à une histoire. Il y a comme une espèce d’interaction constante. Et la bibliothèque, c’est le lieu de rendez-vous pour tisser un lien social avec sa communauté.

[.text-center]
…

L’autonomie, la force intérieure, la cohérence intérieure, tous ces thèmes viennent de la solitude de qualité que j’ai trouvée en faisant ce voyage à vélo et en participant aux bibliothèques publiques.

[.text-center]
…

J’avais comme objectif de participer au maximum de bibliothèques possible. Je suis content. Je crois que ce voyage a été bénéfique pour ma santé mentale, physique et pour réitérer ma passion des bibliothèques publiques. On dit que le voyage à vélo en groupe fait en sorte qu’on parcoure une distance plus rapidement et que le voyage à vélo seul fait en sorte qu’on augmente son estime de soi. Je crois que mon voyage prouve que c’est vrai. À tout le moins, je ne peux pas dire que je suis conscient de toute l’étendue de mon estime de soi, mais je peux dire que j’ai pris conscience que je ne suis pas le nombril du monde.

Avant de passer à la conclusion, je veux faire quelque chose et je sais que mon journal intime était écrit dans un but personnel, servant à me raconter et à me remémorer ce voyage à vélo. Je n’avais donc pas besoin de me présenter. Appelez-moi Kopa. C’est la façon dont mes proches m’appellent. Mon grand-père paternel m’a donné ce surnom en l’honneur de Raymond Kopa, un grand footballeur.
Pour conclure, j’ai décidé que je vais déposer mon journal chez un éditeur pour qu’il soit publié. J’espère donner à d’autres l’envie de participer à sa bibliothèque municipale et d’aller en découvrir. Ma conviction, c’est que participer à sa bibliothèque publique, c’est enrichir la culture de sa communauté, enrichir son savoir-faire et son savoir-être… C’est de se réaliser.
